//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.05 at 01:52:36 PM EST 
//


package edu.emory.cci.pais.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenericSurface complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericSurface">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Surface">
 *       &lt;sequence>
 *         &lt;element name="markupReference" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}MarkupReference" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericSurface", propOrder = {
    "markupReference"
})
public class GenericSurface
    extends Surface
{

    protected GenericSurface.MarkupReference markupReference;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the markupReference property.
     * 
     * @return
     *     possible object is
     *     {@link GenericSurface.MarkupReference }
     *     
     */
    public GenericSurface.MarkupReference getMarkupReference() {
        return markupReference;
    }

    /**
     * Sets the value of the markupReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericSurface.MarkupReference }
     *     
     */
    public void setMarkupReference(GenericSurface.MarkupReference value) {
        this.markupReference = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}MarkupReference" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "markupReference"
    })
    public static class MarkupReference {

        @XmlElement(name = "MarkupReference")
        protected edu.emory.cci.pais.model.MarkupReference markupReference;

        /**
         * Gets the value of the markupReference property.
         * 
         * @return
         *     possible object is
         *     {@link edu.emory.cci.pais.model.MarkupReference }
         *     
         */
        public edu.emory.cci.pais.model.MarkupReference getMarkupReference() {
            return markupReference;
        }

        /**
         * Sets the value of the markupReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.emory.cci.pais.model.MarkupReference }
         *     
         */
        public void setMarkupReference(edu.emory.cci.pais.model.MarkupReference value) {
            this.markupReference = value;
        }

    }

}
