//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.05 at 01:52:36 PM EST 
//


package edu.emory.cci.pais.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Line complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Line">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}GeometricShape">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="startX" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="startY" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="endX" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="endY" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Line")
public class Line
    extends GeometricShape
{

    @XmlAttribute(name = "startX")
    protected Double startX;
    @XmlAttribute(name = "startY")
    protected Double startY;
    @XmlAttribute(name = "endX")
    protected Double endX;
    @XmlAttribute(name = "endY")
    protected Double endY;

    /**
     * Gets the value of the startX property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStartX() {
        return startX;
    }

    /**
     * Sets the value of the startX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStartX(Double value) {
        this.startX = value;
    }

    /**
     * Gets the value of the startY property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStartY() {
        return startY;
    }

    /**
     * Sets the value of the startY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStartY(Double value) {
        this.startY = value;
    }

    /**
     * Gets the value of the endX property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEndX() {
        return endX;
    }

    /**
     * Sets the value of the endX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEndX(Double value) {
        this.endX = value;
    }

    /**
     * Gets the value of the endY property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEndY() {
        return endY;
    }

    /**
     * Sets the value of the endY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEndY(Double value) {
        this.endY = value;
    }

}
