//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.05 at 01:52:36 PM EST 
//


package edu.emory.cci.pais.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Markup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Markup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imageReferenceCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}ImageReference" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="geometricShape" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}GeometricShape" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="surface" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Surface" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="field" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Field" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="provenance" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Provenance" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="annotation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Annotation" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="baseMarkupCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Markup" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="derivedMarkupCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Markup" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="uid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Markup", propOrder = {
    "imageReferenceCollection",
    "geometricShape",
    "surface",
    "field",
    "provenance",
    "annotation",
    "baseMarkupCollection",
    "derivedMarkupCollection"
})
public class Markup {

    protected Markup.ImageReferenceCollection imageReferenceCollection;
    protected Markup.GeometricShape geometricShape;
    protected Markup.Surface surface;
    protected Markup.Field field;
    protected Markup.Provenance provenance;
    protected Markup.Annotation annotation;
    protected Markup.BaseMarkupCollection baseMarkupCollection;
    protected Markup.DerivedMarkupCollection derivedMarkupCollection;
    @XmlAttribute(name = "id")
    protected BigInteger id;
    @XmlAttribute(name = "uid")
    protected String uid;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the imageReferenceCollection property.
     * 
     * @return
     *     possible object is
     *     {@link Markup.ImageReferenceCollection }
     *     
     */
    public Markup.ImageReferenceCollection getImageReferenceCollection() {
        return imageReferenceCollection;
    }

    /**
     * Sets the value of the imageReferenceCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Markup.ImageReferenceCollection }
     *     
     */
    public void setImageReferenceCollection(Markup.ImageReferenceCollection value) {
        this.imageReferenceCollection = value;
    }

    /**
     * Gets the value of the geometricShape property.
     * 
     * @return
     *     possible object is
     *     {@link Markup.GeometricShape }
     *     
     */
    public Markup.GeometricShape getGeometricShape() {
        return geometricShape;
    }

    /**
     * Sets the value of the geometricShape property.
     * 
     * @param value
     *     allowed object is
     *     {@link Markup.GeometricShape }
     *     
     */
    public void setGeometricShape(Markup.GeometricShape value) {
        this.geometricShape = value;
    }

    /**
     * Gets the value of the surface property.
     * 
     * @return
     *     possible object is
     *     {@link Markup.Surface }
     *     
     */
    public Markup.Surface getSurface() {
        return surface;
    }

    /**
     * Sets the value of the surface property.
     * 
     * @param value
     *     allowed object is
     *     {@link Markup.Surface }
     *     
     */
    public void setSurface(Markup.Surface value) {
        this.surface = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link Markup.Field }
     *     
     */
    public Markup.Field getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link Markup.Field }
     *     
     */
    public void setField(Markup.Field value) {
        this.field = value;
    }

    /**
     * Gets the value of the provenance property.
     * 
     * @return
     *     possible object is
     *     {@link Markup.Provenance }
     *     
     */
    public Markup.Provenance getProvenance() {
        return provenance;
    }

    /**
     * Sets the value of the provenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Markup.Provenance }
     *     
     */
    public void setProvenance(Markup.Provenance value) {
        this.provenance = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link Markup.Annotation }
     *     
     */
    public Markup.Annotation getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Markup.Annotation }
     *     
     */
    public void setAnnotation(Markup.Annotation value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the baseMarkupCollection property.
     * 
     * @return
     *     possible object is
     *     {@link Markup.BaseMarkupCollection }
     *     
     */
    public Markup.BaseMarkupCollection getBaseMarkupCollection() {
        return baseMarkupCollection;
    }

    /**
     * Sets the value of the baseMarkupCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Markup.BaseMarkupCollection }
     *     
     */
    public void setBaseMarkupCollection(Markup.BaseMarkupCollection value) {
        this.baseMarkupCollection = value;
    }

    /**
     * Gets the value of the derivedMarkupCollection property.
     * 
     * @return
     *     possible object is
     *     {@link Markup.DerivedMarkupCollection }
     *     
     */
    public Markup.DerivedMarkupCollection getDerivedMarkupCollection() {
        return derivedMarkupCollection;
    }

    /**
     * Sets the value of the derivedMarkupCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Markup.DerivedMarkupCollection }
     *     
     */
    public void setDerivedMarkupCollection(Markup.DerivedMarkupCollection value) {
        this.derivedMarkupCollection = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Annotation" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "annotation"
    })
    public static class Annotation {

        @XmlElement(name = "Annotation")
        protected edu.emory.cci.pais.model.Annotation annotation;

        /**
         * Gets the value of the annotation property.
         * 
         * @return
         *     possible object is
         *     {@link edu.emory.cci.pais.model.Annotation }
         *     
         */
        public edu.emory.cci.pais.model.Annotation getAnnotation() {
            return annotation;
        }

        /**
         * Sets the value of the annotation property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.emory.cci.pais.model.Annotation }
         *     
         */
        public void setAnnotation(edu.emory.cci.pais.model.Annotation value) {
            this.annotation = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Markup" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "markup"
    })
    public static class BaseMarkupCollection {

        @XmlElement(name = "Markup")
        protected List<Markup> markup;

        /**
         * Gets the value of the markup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the markup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarkup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Markup }
         * 
         * 
         */
        public List<Markup> getMarkup() {
            if (markup == null) {
                markup = new ArrayList<Markup>();
            }
            return this.markup;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Markup" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "markup"
    })
    public static class DerivedMarkupCollection {

        @XmlElement(name = "Markup")
        protected List<Markup> markup;

        /**
         * Gets the value of the markup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the markup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarkup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Markup }
         * 
         * 
         */
        public List<Markup> getMarkup() {
            if (markup == null) {
                markup = new ArrayList<Markup>();
            }
            return this.markup;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Field" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "field"
    })
    public static class Field {

        @XmlElement(name = "Field")
        protected edu.emory.cci.pais.model.Field field;

        /**
         * Gets the value of the field property.
         * 
         * @return
         *     possible object is
         *     {@link edu.emory.cci.pais.model.Field }
         *     
         */
        public edu.emory.cci.pais.model.Field getField() {
            return field;
        }

        /**
         * Sets the value of the field property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.emory.cci.pais.model.Field }
         *     
         */
        public void setField(edu.emory.cci.pais.model.Field value) {
            this.field = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}GeometricShape" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "geometricShape"
    })
    public static class GeometricShape {

        @XmlElement(name = "GeometricShape")
        protected edu.emory.cci.pais.model.GeometricShape geometricShape;

        /**
         * Gets the value of the geometricShape property.
         * 
         * @return
         *     possible object is
         *     {@link edu.emory.cci.pais.model.GeometricShape }
         *     
         */
        public edu.emory.cci.pais.model.GeometricShape getGeometricShape() {
            return geometricShape;
        }

        /**
         * Sets the value of the geometricShape property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.emory.cci.pais.model.GeometricShape }
         *     
         */
        public void setGeometricShape(edu.emory.cci.pais.model.GeometricShape value) {
            this.geometricShape = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}ImageReference" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imageReference"
    })
    public static class ImageReferenceCollection {

        @XmlElement(name = "ImageReference")
        protected List<ImageReference> imageReference;

        /**
         * Gets the value of the imageReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imageReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImageReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImageReference }
         * 
         * 
         */
        public List<ImageReference> getImageReference() {
            if (imageReference == null) {
                imageReference = new ArrayList<ImageReference>();
            }
            return this.imageReference;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Provenance" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "provenance"
    })
    public static class Provenance {

        @XmlElement(name = "Provenance")
        protected edu.emory.cci.pais.model.Provenance provenance;

        /**
         * Gets the value of the provenance property.
         * 
         * @return
         *     possible object is
         *     {@link edu.emory.cci.pais.model.Provenance }
         *     
         */
        public edu.emory.cci.pais.model.Provenance getProvenance() {
            return provenance;
        }

        /**
         * Sets the value of the provenance property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.emory.cci.pais.model.Provenance }
         *     
         */
        public void setProvenance(edu.emory.cci.pais.model.Provenance value) {
            this.provenance = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{gme://caCORE.caCORE/3.2/edu.emory.cci.pais}Surface" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "surface"
    })
    public static class Surface {

        @XmlElement(name = "Surface")
        protected edu.emory.cci.pais.model.Surface surface;

        /**
         * Gets the value of the surface property.
         * 
         * @return
         *     possible object is
         *     {@link edu.emory.cci.pais.model.Surface }
         *     
         */
        public edu.emory.cci.pais.model.Surface getSurface() {
            return surface;
        }

        /**
         * Sets the value of the surface property.
         * 
         * @param value
         *     allowed object is
         *     {@link edu.emory.cci.pais.model.Surface }
         *     
         */
        public void setSurface(edu.emory.cci.pais.model.Surface value) {
            this.surface = value;
        }

    }

}
