//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.05 at 01:52:36 PM EST 
//


package edu.emory.cci.pais.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.emory.cci.pais.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AnnotationReference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "AnnotationReference");
    private final static QName _Circle_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Circle");
    private final static QName _Nominal_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Nominal");
    private final static QName _User_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "User");
    private final static QName _Project_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Project");
    private final static QName _Collection_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Collection");
    private final static QName _MultiPolygon_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "MultiPolygon");
    private final static QName _Quantification_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Quantification");
    private final static QName _Calculation_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Calculation");
    private final static QName _Ellipse_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Ellipse");
    private final static QName _Histogram_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Histogram");
    private final static QName _Markup_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Markup");
    private final static QName _DICOMSegmentation_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "DICOMSegmentation");
    private final static QName _Region_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Region");
    private final static QName _Algorithm_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Algorithm");
    private final static QName _DICOMImageReference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "DICOMImageReference");
    private final static QName _Parameter_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Parameter");
    private final static QName _InputFileReference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "InputFileReference");
    private final static QName _Array_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Array");
    private final static QName _Matrix_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Matrix");
    private final static QName _Observation_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Observation");
    private final static QName _ImageReference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "ImageReference");
    private final static QName _MultiPoint_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "MultiPoint");
    private final static QName _MarkupBinary_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "MarkupBinary");
    private final static QName _GenericSurface_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "GenericSurface");
    private final static QName _Ordinal_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Ordinal");
    private final static QName _Subject_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Subject");
    private final static QName _FileReference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "FileReference");
    private final static QName _Scalar_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Scalar");
    private final static QName _AnatomicEntityCharacteristic_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "AnatomicEntityCharacteristic");
    private final static QName _Polyline_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Polyline");
    private final static QName _PAIS_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "PAIS");
    private final static QName _Binary_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Binary");
    private final static QName _Mask_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Mask");
    private final static QName _MultiLine_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "MultiLine");
    private final static QName _AnatomicEntity_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "AnatomicEntity");
    private final static QName _URI_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "URI");
    private final static QName _WholeSlideImageReference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "WholeSlideImageReference");
    private final static QName _Interval_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Interval");
    private final static QName _Specimen_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Specimen");
    private final static QName _Surface_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Surface");
    private final static QName _ImageStudy_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "ImageStudy");
    private final static QName _TMAImageReference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "TMAImageReference");
    private final static QName _Inference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Inference");
    private final static QName _Polygon_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Polygon");
    private final static QName _Line_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Line");
    private final static QName _MicroscopyImageReference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "MicroscopyImageReference");
    private final static QName _Image_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Image");
    private final static QName _Patient_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Patient");
    private final static QName _ObservationCharacteristic_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "ObservationCharacteristic");
    private final static QName _Equipment_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Equipment");
    private final static QName _Field_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Field");
    private final static QName _MarkupURI_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "MarkupURI");
    private final static QName _MarkupFileReference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "MarkupFileReference");
    private final static QName _Rectangle_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Rectangle");
    private final static QName _GeometricShape_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "GeometricShape");
    private final static QName _CalculationResult_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "CalculationResult");
    private final static QName _MarkupReference_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "MarkupReference");
    private final static QName _Point_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Point");
    private final static QName _Group_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Group");
    private final static QName _Provenance_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Provenance");
    private final static QName _Annotation_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Annotation");
    private final static QName _ImageSeries_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "ImageSeries");
    private final static QName _Ratio_QNAME = new QName("gme://caCORE.caCORE/3.2/edu.emory.cci.pais", "Ratio");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.emory.cci.pais.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PAIS }
     * 
     */
    public PAIS createPAIS() {
        return new PAIS();
    }

    /**
     * Create an instance of {@link Markup }
     * 
     */
    public Markup createMarkup() {
        return new Markup();
    }

    /**
     * Create an instance of {@link ImageReference }
     * 
     */
    public ImageReference createImageReference() {
        return new ImageReference();
    }

    /**
     * Create an instance of {@link AnatomicEntityCharacteristic }
     * 
     */
    public AnatomicEntityCharacteristic createAnatomicEntityCharacteristic() {
        return new AnatomicEntityCharacteristic();
    }

    /**
     * Create an instance of {@link DICOMImageReference }
     * 
     */
    public DICOMImageReference createDICOMImageReference() {
        return new DICOMImageReference();
    }

    /**
     * Create an instance of {@link Observation }
     * 
     */
    public Observation createObservation() {
        return new Observation();
    }

    /**
     * Create an instance of {@link ObservationCharacteristic }
     * 
     */
    public ObservationCharacteristic createObservationCharacteristic() {
        return new ObservationCharacteristic();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Annotation }
     * 
     */
    public edu.emory.cci.pais.model.Annotation createAnnotation() {
        return new edu.emory.cci.pais.model.Annotation();
    }

    /**
     * Create an instance of {@link Calculation }
     * 
     */
    public Calculation createCalculation() {
        return new Calculation();
    }

    /**
     * Create an instance of {@link AnatomicEntity }
     * 
     */
    public AnatomicEntity createAnatomicEntity() {
        return new AnatomicEntity();
    }

    /**
     * Create an instance of {@link DICOMSegmentation }
     * 
     */
    public DICOMSegmentation createDICOMSegmentation() {
        return new DICOMSegmentation();
    }

    /**
     * Create an instance of {@link GenericSurface }
     * 
     */
    public GenericSurface createGenericSurface() {
        return new GenericSurface();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Provenance }
     * 
     */
    public edu.emory.cci.pais.model.Provenance createProvenance() {
        return new edu.emory.cci.pais.model.Provenance();
    }

    /**
     * Create an instance of {@link ImageSeries }
     * 
     */
    public ImageSeries createImageSeries() {
        return new ImageSeries();
    }

    /**
     * Create an instance of {@link ImageStudy }
     * 
     */
    public ImageStudy createImageStudy() {
        return new ImageStudy();
    }

    /**
     * Create an instance of {@link Mask }
     * 
     */
    public Mask createMask() {
        return new Mask();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Surface }
     * 
     */
    public edu.emory.cci.pais.model.Surface createSurface() {
        return new edu.emory.cci.pais.model.Surface();
    }

    /**
     * Create an instance of {@link Nominal }
     * 
     */
    public Nominal createNominal() {
        return new Nominal();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Group }
     * 
     */
    public edu.emory.cci.pais.model.Group createGroup() {
        return new edu.emory.cci.pais.model.Group();
    }

    /**
     * Create an instance of {@link Polyline }
     * 
     */
    public Polyline createPolyline() {
        return new Polyline();
    }

    /**
     * Create an instance of {@link Array }
     * 
     */
    public Array createArray() {
        return new Array();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link MultiPoint }
     * 
     */
    public MultiPoint createMultiPoint() {
        return new MultiPoint();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Region }
     * 
     */
    public edu.emory.cci.pais.model.Region createRegion() {
        return new edu.emory.cci.pais.model.Region();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Subject }
     * 
     */
    public edu.emory.cci.pais.model.Subject createSubject() {
        return new edu.emory.cci.pais.model.Subject();
    }

    /**
     * Create an instance of {@link Histogram }
     * 
     */
    public Histogram createHistogram() {
        return new Histogram();
    }

    /**
     * Create an instance of {@link URI }
     * 
     */
    public URI createURI() {
        return new URI();
    }

    /**
     * Create an instance of {@link Rectangle }
     * 
     */
    public Rectangle createRectangle() {
        return new Rectangle();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Quantification }
     * 
     */
    public edu.emory.cci.pais.model.Quantification createQuantification() {
        return new edu.emory.cci.pais.model.Quantification();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Algorithm }
     * 
     */
    public edu.emory.cci.pais.model.Algorithm createAlgorithm() {
        return new edu.emory.cci.pais.model.Algorithm();
    }

    /**
     * Create an instance of {@link MarkupBinary }
     * 
     */
    public MarkupBinary createMarkupBinary() {
        return new MarkupBinary();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link Ordinal }
     * 
     */
    public Ordinal createOrdinal() {
        return new Ordinal();
    }

    /**
     * Create an instance of {@link MicroscopyImageReference }
     * 
     */
    public MicroscopyImageReference createMicroscopyImageReference() {
        return new MicroscopyImageReference();
    }

    /**
     * Create an instance of {@link Interval }
     * 
     */
    public Interval createInterval() {
        return new Interval();
    }

    /**
     * Create an instance of {@link MultiLine }
     * 
     */
    public MultiLine createMultiLine() {
        return new MultiLine();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.CalculationResult }
     * 
     */
    public edu.emory.cci.pais.model.CalculationResult createCalculationResult() {
        return new edu.emory.cci.pais.model.CalculationResult();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link InputFileReference }
     * 
     */
    public InputFileReference createInputFileReference() {
        return new InputFileReference();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.GeometricShape }
     * 
     */
    public edu.emory.cci.pais.model.GeometricShape createGeometricShape() {
        return new edu.emory.cci.pais.model.GeometricShape();
    }

    /**
     * Create an instance of {@link Matrix }
     * 
     */
    public Matrix createMatrix() {
        return new Matrix();
    }

    /**
     * Create an instance of {@link WholeSlideImageReference }
     * 
     */
    public WholeSlideImageReference createWholeSlideImageReference() {
        return new WholeSlideImageReference();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Specimen }
     * 
     */
    public edu.emory.cci.pais.model.Specimen createSpecimen() {
        return new edu.emory.cci.pais.model.Specimen();
    }

    /**
     * Create an instance of {@link MarkupURI }
     * 
     */
    public MarkupURI createMarkupURI() {
        return new MarkupURI();
    }

    /**
     * Create an instance of {@link AnnotationReference }
     * 
     */
    public AnnotationReference createAnnotationReference() {
        return new AnnotationReference();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.MarkupReference }
     * 
     */
    public edu.emory.cci.pais.model.MarkupReference createMarkupReference() {
        return new edu.emory.cci.pais.model.MarkupReference();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Inference }
     * 
     */
    public Inference createInference() {
        return new Inference();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.User }
     * 
     */
    public edu.emory.cci.pais.model.User createUser() {
        return new edu.emory.cci.pais.model.User();
    }

    /**
     * Create an instance of {@link Binary }
     * 
     */
    public Binary createBinary() {
        return new Binary();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Project }
     * 
     */
    public edu.emory.cci.pais.model.Project createProject() {
        return new edu.emory.cci.pais.model.Project();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Field }
     * 
     */
    public edu.emory.cci.pais.model.Field createField() {
        return new edu.emory.cci.pais.model.Field();
    }

    /**
     * Create an instance of {@link Scalar }
     * 
     */
    public Scalar createScalar() {
        return new Scalar();
    }

    /**
     * Create an instance of {@link MultiPolygon }
     * 
     */
    public MultiPolygon createMultiPolygon() {
        return new MultiPolygon();
    }

    /**
     * Create an instance of {@link Ratio }
     * 
     */
    public Ratio createRatio() {
        return new Ratio();
    }

    /**
     * Create an instance of {@link TMAImageReference }
     * 
     */
    public TMAImageReference createTMAImageReference() {
        return new TMAImageReference();
    }

    /**
     * Create an instance of {@link Polygon }
     * 
     */
    public Polygon createPolygon() {
        return new Polygon();
    }

    /**
     * Create an instance of {@link Collection }
     * 
     */
    public Collection createCollection() {
        return new Collection();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Equipment }
     * 
     */
    public edu.emory.cci.pais.model.Equipment createEquipment() {
        return new edu.emory.cci.pais.model.Equipment();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Ellipse }
     * 
     */
    public Ellipse createEllipse() {
        return new Ellipse();
    }

    /**
     * Create an instance of {@link Circle }
     * 
     */
    public Circle createCircle() {
        return new Circle();
    }

    /**
     * Create an instance of {@link FileReference }
     * 
     */
    public FileReference createFileReference() {
        return new FileReference();
    }

    /**
     * Create an instance of {@link MarkupFileReference }
     * 
     */
    public MarkupFileReference createMarkupFileReference() {
        return new MarkupFileReference();
    }

    /**
     * Create an instance of {@link PAIS.Project }
     * 
     */
    public PAIS.Project createPAISProject() {
        return new PAIS.Project();
    }

    /**
     * Create an instance of {@link PAIS.Collections }
     * 
     */
    public PAIS.Collections createPAISCollections() {
        return new PAIS.Collections();
    }

    /**
     * Create an instance of {@link PAIS.Group }
     * 
     */
    public PAIS.Group createPAISGroup() {
        return new PAIS.Group();
    }

    /**
     * Create an instance of {@link PAIS.User }
     * 
     */
    public PAIS.User createPAISUser() {
        return new PAIS.User();
    }

    /**
     * Create an instance of {@link PAIS.ImageReferenceCollection }
     * 
     */
    public PAIS.ImageReferenceCollection createPAISImageReferenceCollection() {
        return new PAIS.ImageReferenceCollection();
    }

    /**
     * Create an instance of {@link PAIS.MarkupCollection }
     * 
     */
    public PAIS.MarkupCollection createPAISMarkupCollection() {
        return new PAIS.MarkupCollection();
    }

    /**
     * Create an instance of {@link PAIS.AnnotationCollection }
     * 
     */
    public PAIS.AnnotationCollection createPAISAnnotationCollection() {
        return new PAIS.AnnotationCollection();
    }

    /**
     * Create an instance of {@link PAIS.ProvenanceCollection }
     * 
     */
    public PAIS.ProvenanceCollection createPAISProvenanceCollection() {
        return new PAIS.ProvenanceCollection();
    }

    /**
     * Create an instance of {@link PAIS.AnnotationReferenceCollection }
     * 
     */
    public PAIS.AnnotationReferenceCollection createPAISAnnotationReferenceCollection() {
        return new PAIS.AnnotationReferenceCollection();
    }

    /**
     * Create an instance of {@link Markup.ImageReferenceCollection }
     * 
     */
    public Markup.ImageReferenceCollection createMarkupImageReferenceCollection() {
        return new Markup.ImageReferenceCollection();
    }

    /**
     * Create an instance of {@link Markup.GeometricShape }
     * 
     */
    public Markup.GeometricShape createMarkupGeometricShape() {
        return new Markup.GeometricShape();
    }

    /**
     * Create an instance of {@link Markup.Surface }
     * 
     */
    public Markup.Surface createMarkupSurface() {
        return new Markup.Surface();
    }

    /**
     * Create an instance of {@link Markup.Field }
     * 
     */
    public Markup.Field createMarkupField() {
        return new Markup.Field();
    }

    /**
     * Create an instance of {@link Markup.Provenance }
     * 
     */
    public Markup.Provenance createMarkupProvenance() {
        return new Markup.Provenance();
    }

    /**
     * Create an instance of {@link Markup.Annotation }
     * 
     */
    public Markup.Annotation createMarkupAnnotation() {
        return new Markup.Annotation();
    }

    /**
     * Create an instance of {@link Markup.BaseMarkupCollection }
     * 
     */
    public Markup.BaseMarkupCollection createMarkupBaseMarkupCollection() {
        return new Markup.BaseMarkupCollection();
    }

    /**
     * Create an instance of {@link Markup.DerivedMarkupCollection }
     * 
     */
    public Markup.DerivedMarkupCollection createMarkupDerivedMarkupCollection() {
        return new Markup.DerivedMarkupCollection();
    }

    /**
     * Create an instance of {@link ImageReference.Subject }
     * 
     */
    public ImageReference.Subject createImageReferenceSubject() {
        return new ImageReference.Subject();
    }

    /**
     * Create an instance of {@link ImageReference.Specimen }
     * 
     */
    public ImageReference.Specimen createImageReferenceSpecimen() {
        return new ImageReference.Specimen();
    }

    /**
     * Create an instance of {@link ImageReference.AnatomicEntityCollection }
     * 
     */
    public ImageReference.AnatomicEntityCollection createImageReferenceAnatomicEntityCollection() {
        return new ImageReference.AnatomicEntityCollection();
    }

    /**
     * Create an instance of {@link ImageReference.Equipment }
     * 
     */
    public ImageReference.Equipment createImageReferenceEquipment() {
        return new ImageReference.Equipment();
    }

    /**
     * Create an instance of {@link ImageReference.Region }
     * 
     */
    public ImageReference.Region createImageReferenceRegion() {
        return new ImageReference.Region();
    }

    /**
     * Create an instance of {@link AnatomicEntityCharacteristic.Quantification }
     * 
     */
    public AnatomicEntityCharacteristic.Quantification createAnatomicEntityCharacteristicQuantification() {
        return new AnatomicEntityCharacteristic.Quantification();
    }

    /**
     * Create an instance of {@link DICOMImageReference.Study }
     * 
     */
    public DICOMImageReference.Study createDICOMImageReferenceStudy() {
        return new DICOMImageReference.Study();
    }

    /**
     * Create an instance of {@link Observation.ObservationCharacteristicCollection }
     * 
     */
    public Observation.ObservationCharacteristicCollection createObservationObservationCharacteristicCollection() {
        return new Observation.ObservationCharacteristicCollection();
    }

    /**
     * Create an instance of {@link Observation.Provenance }
     * 
     */
    public Observation.Provenance createObservationProvenance() {
        return new Observation.Provenance();
    }

    /**
     * Create an instance of {@link Observation.Quantification }
     * 
     */
    public Observation.Quantification createObservationQuantification() {
        return new Observation.Quantification();
    }

    /**
     * Create an instance of {@link ObservationCharacteristic.Quantification }
     * 
     */
    public ObservationCharacteristic.Quantification createObservationCharacteristicQuantification() {
        return new ObservationCharacteristic.Quantification();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Annotation.MarkupCollection }
     * 
     */
    public edu.emory.cci.pais.model.Annotation.MarkupCollection createAnnotationMarkupCollection() {
        return new edu.emory.cci.pais.model.Annotation.MarkupCollection();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Annotation.CalculationCollection }
     * 
     */
    public edu.emory.cci.pais.model.Annotation.CalculationCollection createAnnotationCalculationCollection() {
        return new edu.emory.cci.pais.model.Annotation.CalculationCollection();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Annotation.ObservationCollection }
     * 
     */
    public edu.emory.cci.pais.model.Annotation.ObservationCollection createAnnotationObservationCollection() {
        return new edu.emory.cci.pais.model.Annotation.ObservationCollection();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Annotation.InferenceCollection }
     * 
     */
    public edu.emory.cci.pais.model.Annotation.InferenceCollection createAnnotationInferenceCollection() {
        return new edu.emory.cci.pais.model.Annotation.InferenceCollection();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Annotation.BaseAnnotationCollection }
     * 
     */
    public edu.emory.cci.pais.model.Annotation.BaseAnnotationCollection createAnnotationBaseAnnotationCollection() {
        return new edu.emory.cci.pais.model.Annotation.BaseAnnotationCollection();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Annotation.DerivedAnnotationCollection }
     * 
     */
    public edu.emory.cci.pais.model.Annotation.DerivedAnnotationCollection createAnnotationDerivedAnnotationCollection() {
        return new edu.emory.cci.pais.model.Annotation.DerivedAnnotationCollection();
    }

    /**
     * Create an instance of {@link Calculation.CalculationResult }
     * 
     */
    public Calculation.CalculationResult createCalculationCalculationResult() {
        return new Calculation.CalculationResult();
    }

    /**
     * Create an instance of {@link Calculation.Provenance }
     * 
     */
    public Calculation.Provenance createCalculationProvenance() {
        return new Calculation.Provenance();
    }

    /**
     * Create an instance of {@link AnatomicEntity.AnatomicEntityCharacteristicCollection }
     * 
     */
    public AnatomicEntity.AnatomicEntityCharacteristicCollection createAnatomicEntityAnatomicEntityCharacteristicCollection() {
        return new AnatomicEntity.AnatomicEntityCharacteristicCollection();
    }

    /**
     * Create an instance of {@link DICOMSegmentation.MarkupReference }
     * 
     */
    public DICOMSegmentation.MarkupReference createDICOMSegmentationMarkupReference() {
        return new DICOMSegmentation.MarkupReference();
    }

    /**
     * Create an instance of {@link GenericSurface.MarkupReference }
     * 
     */
    public GenericSurface.MarkupReference createGenericSurfaceMarkupReference() {
        return new GenericSurface.MarkupReference();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Provenance.Algorithm }
     * 
     */
    public edu.emory.cci.pais.model.Provenance.Algorithm createProvenanceAlgorithm() {
        return new edu.emory.cci.pais.model.Provenance.Algorithm();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Provenance.ParameterCollection }
     * 
     */
    public edu.emory.cci.pais.model.Provenance.ParameterCollection createProvenanceParameterCollection() {
        return new edu.emory.cci.pais.model.Provenance.ParameterCollection();
    }

    /**
     * Create an instance of {@link edu.emory.cci.pais.model.Provenance.InputFileReferenceCollection }
     * 
     */
    public edu.emory.cci.pais.model.Provenance.InputFileReferenceCollection createProvenanceInputFileReferenceCollection() {
        return new edu.emory.cci.pais.model.Provenance.InputFileReferenceCollection();
    }

    /**
     * Create an instance of {@link ImageSeries.ImageCollection }
     * 
     */
    public ImageSeries.ImageCollection createImageSeriesImageCollection() {
        return new ImageSeries.ImageCollection();
    }

    /**
     * Create an instance of {@link ImageStudy.Series }
     * 
     */
    public ImageStudy.Series createImageStudySeries() {
        return new ImageStudy.Series();
    }

    /**
     * Create an instance of {@link Mask.MarkupReference }
     * 
     */
    public Mask.MarkupReference createMaskMarkupReference() {
        return new Mask.MarkupReference();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "AnnotationReference")
    public JAXBElement<AnnotationReference> createAnnotationReference(AnnotationReference value) {
        return new JAXBElement<AnnotationReference>(_AnnotationReference_QNAME, AnnotationReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Circle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Circle")
    public JAXBElement<Circle> createCircle(Circle value) {
        return new JAXBElement<Circle>(_Circle_QNAME, Circle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Nominal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Nominal")
    public JAXBElement<Nominal> createNominal(Nominal value) {
        return new JAXBElement<Nominal>(_Nominal_QNAME, Nominal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "User")
    public JAXBElement<edu.emory.cci.pais.model.User> createUser(edu.emory.cci.pais.model.User value) {
        return new JAXBElement<edu.emory.cci.pais.model.User>(_User_QNAME, edu.emory.cci.pais.model.User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Project }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Project")
    public JAXBElement<edu.emory.cci.pais.model.Project> createProject(edu.emory.cci.pais.model.Project value) {
        return new JAXBElement<edu.emory.cci.pais.model.Project>(_Project_QNAME, edu.emory.cci.pais.model.Project.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Collection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Collection")
    public JAXBElement<Collection> createCollection(Collection value) {
        return new JAXBElement<Collection>(_Collection_QNAME, Collection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiPolygon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "MultiPolygon")
    public JAXBElement<MultiPolygon> createMultiPolygon(MultiPolygon value) {
        return new JAXBElement<MultiPolygon>(_MultiPolygon_QNAME, MultiPolygon.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Quantification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Quantification")
    public JAXBElement<edu.emory.cci.pais.model.Quantification> createQuantification(edu.emory.cci.pais.model.Quantification value) {
        return new JAXBElement<edu.emory.cci.pais.model.Quantification>(_Quantification_QNAME, edu.emory.cci.pais.model.Quantification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Calculation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Calculation")
    public JAXBElement<Calculation> createCalculation(Calculation value) {
        return new JAXBElement<Calculation>(_Calculation_QNAME, Calculation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ellipse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Ellipse")
    public JAXBElement<Ellipse> createEllipse(Ellipse value) {
        return new JAXBElement<Ellipse>(_Ellipse_QNAME, Ellipse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Histogram }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Histogram")
    public JAXBElement<Histogram> createHistogram(Histogram value) {
        return new JAXBElement<Histogram>(_Histogram_QNAME, Histogram.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Markup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Markup")
    public JAXBElement<Markup> createMarkup(Markup value) {
        return new JAXBElement<Markup>(_Markup_QNAME, Markup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DICOMSegmentation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "DICOMSegmentation")
    public JAXBElement<DICOMSegmentation> createDICOMSegmentation(DICOMSegmentation value) {
        return new JAXBElement<DICOMSegmentation>(_DICOMSegmentation_QNAME, DICOMSegmentation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Region }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Region")
    public JAXBElement<edu.emory.cci.pais.model.Region> createRegion(edu.emory.cci.pais.model.Region value) {
        return new JAXBElement<edu.emory.cci.pais.model.Region>(_Region_QNAME, edu.emory.cci.pais.model.Region.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Algorithm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Algorithm")
    public JAXBElement<edu.emory.cci.pais.model.Algorithm> createAlgorithm(edu.emory.cci.pais.model.Algorithm value) {
        return new JAXBElement<edu.emory.cci.pais.model.Algorithm>(_Algorithm_QNAME, edu.emory.cci.pais.model.Algorithm.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DICOMImageReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "DICOMImageReference")
    public JAXBElement<DICOMImageReference> createDICOMImageReference(DICOMImageReference value) {
        return new JAXBElement<DICOMImageReference>(_DICOMImageReference_QNAME, DICOMImageReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Parameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Parameter")
    public JAXBElement<Parameter> createParameter(Parameter value) {
        return new JAXBElement<Parameter>(_Parameter_QNAME, Parameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputFileReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "InputFileReference")
    public JAXBElement<InputFileReference> createInputFileReference(InputFileReference value) {
        return new JAXBElement<InputFileReference>(_InputFileReference_QNAME, InputFileReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Array }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Array")
    public JAXBElement<Array> createArray(Array value) {
        return new JAXBElement<Array>(_Array_QNAME, Array.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matrix }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Matrix")
    public JAXBElement<Matrix> createMatrix(Matrix value) {
        return new JAXBElement<Matrix>(_Matrix_QNAME, Matrix.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Observation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Observation")
    public JAXBElement<Observation> createObservation(Observation value) {
        return new JAXBElement<Observation>(_Observation_QNAME, Observation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "ImageReference")
    public JAXBElement<ImageReference> createImageReference(ImageReference value) {
        return new JAXBElement<ImageReference>(_ImageReference_QNAME, ImageReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiPoint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "MultiPoint")
    public JAXBElement<MultiPoint> createMultiPoint(MultiPoint value) {
        return new JAXBElement<MultiPoint>(_MultiPoint_QNAME, MultiPoint.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupBinary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "MarkupBinary")
    public JAXBElement<MarkupBinary> createMarkupBinary(MarkupBinary value) {
        return new JAXBElement<MarkupBinary>(_MarkupBinary_QNAME, MarkupBinary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericSurface }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "GenericSurface")
    public JAXBElement<GenericSurface> createGenericSurface(GenericSurface value) {
        return new JAXBElement<GenericSurface>(_GenericSurface_QNAME, GenericSurface.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ordinal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Ordinal")
    public JAXBElement<Ordinal> createOrdinal(Ordinal value) {
        return new JAXBElement<Ordinal>(_Ordinal_QNAME, Ordinal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Subject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Subject")
    public JAXBElement<edu.emory.cci.pais.model.Subject> createSubject(edu.emory.cci.pais.model.Subject value) {
        return new JAXBElement<edu.emory.cci.pais.model.Subject>(_Subject_QNAME, edu.emory.cci.pais.model.Subject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "FileReference")
    public JAXBElement<FileReference> createFileReference(FileReference value) {
        return new JAXBElement<FileReference>(_FileReference_QNAME, FileReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Scalar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Scalar")
    public JAXBElement<Scalar> createScalar(Scalar value) {
        return new JAXBElement<Scalar>(_Scalar_QNAME, Scalar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnatomicEntityCharacteristic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "AnatomicEntityCharacteristic")
    public JAXBElement<AnatomicEntityCharacteristic> createAnatomicEntityCharacteristic(AnatomicEntityCharacteristic value) {
        return new JAXBElement<AnatomicEntityCharacteristic>(_AnatomicEntityCharacteristic_QNAME, AnatomicEntityCharacteristic.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Polyline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Polyline")
    public JAXBElement<Polyline> createPolyline(Polyline value) {
        return new JAXBElement<Polyline>(_Polyline_QNAME, Polyline.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PAIS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "PAIS")
    public JAXBElement<PAIS> createPAIS(PAIS value) {
        return new JAXBElement<PAIS>(_PAIS_QNAME, PAIS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Binary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Binary")
    public JAXBElement<Binary> createBinary(Binary value) {
        return new JAXBElement<Binary>(_Binary_QNAME, Binary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mask }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Mask")
    public JAXBElement<Mask> createMask(Mask value) {
        return new JAXBElement<Mask>(_Mask_QNAME, Mask.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "MultiLine")
    public JAXBElement<MultiLine> createMultiLine(MultiLine value) {
        return new JAXBElement<MultiLine>(_MultiLine_QNAME, MultiLine.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnatomicEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "AnatomicEntity")
    public JAXBElement<AnatomicEntity> createAnatomicEntity(AnatomicEntity value) {
        return new JAXBElement<AnatomicEntity>(_AnatomicEntity_QNAME, AnatomicEntity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link URI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "URI")
    public JAXBElement<URI> createURI(URI value) {
        return new JAXBElement<URI>(_URI_QNAME, URI.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WholeSlideImageReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "WholeSlideImageReference")
    public JAXBElement<WholeSlideImageReference> createWholeSlideImageReference(WholeSlideImageReference value) {
        return new JAXBElement<WholeSlideImageReference>(_WholeSlideImageReference_QNAME, WholeSlideImageReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interval }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Interval")
    public JAXBElement<Interval> createInterval(Interval value) {
        return new JAXBElement<Interval>(_Interval_QNAME, Interval.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Specimen }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Specimen")
    public JAXBElement<edu.emory.cci.pais.model.Specimen> createSpecimen(edu.emory.cci.pais.model.Specimen value) {
        return new JAXBElement<edu.emory.cci.pais.model.Specimen>(_Specimen_QNAME, edu.emory.cci.pais.model.Specimen.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Surface }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Surface")
    public JAXBElement<edu.emory.cci.pais.model.Surface> createSurface(edu.emory.cci.pais.model.Surface value) {
        return new JAXBElement<edu.emory.cci.pais.model.Surface>(_Surface_QNAME, edu.emory.cci.pais.model.Surface.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageStudy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "ImageStudy")
    public JAXBElement<ImageStudy> createImageStudy(ImageStudy value) {
        return new JAXBElement<ImageStudy>(_ImageStudy_QNAME, ImageStudy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMAImageReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "TMAImageReference")
    public JAXBElement<TMAImageReference> createTMAImageReference(TMAImageReference value) {
        return new JAXBElement<TMAImageReference>(_TMAImageReference_QNAME, TMAImageReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Inference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Inference")
    public JAXBElement<Inference> createInference(Inference value) {
        return new JAXBElement<Inference>(_Inference_QNAME, Inference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Polygon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Polygon")
    public JAXBElement<Polygon> createPolygon(Polygon value) {
        return new JAXBElement<Polygon>(_Polygon_QNAME, Polygon.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Line }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Line")
    public JAXBElement<Line> createLine(Line value) {
        return new JAXBElement<Line>(_Line_QNAME, Line.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MicroscopyImageReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "MicroscopyImageReference")
    public JAXBElement<MicroscopyImageReference> createMicroscopyImageReference(MicroscopyImageReference value) {
        return new JAXBElement<MicroscopyImageReference>(_MicroscopyImageReference_QNAME, MicroscopyImageReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Image")
    public JAXBElement<Image> createImage(Image value) {
        return new JAXBElement<Image>(_Image_QNAME, Image.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Patient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Patient")
    public JAXBElement<Patient> createPatient(Patient value) {
        return new JAXBElement<Patient>(_Patient_QNAME, Patient.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObservationCharacteristic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "ObservationCharacteristic")
    public JAXBElement<ObservationCharacteristic> createObservationCharacteristic(ObservationCharacteristic value) {
        return new JAXBElement<ObservationCharacteristic>(_ObservationCharacteristic_QNAME, ObservationCharacteristic.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Equipment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Equipment")
    public JAXBElement<edu.emory.cci.pais.model.Equipment> createEquipment(edu.emory.cci.pais.model.Equipment value) {
        return new JAXBElement<edu.emory.cci.pais.model.Equipment>(_Equipment_QNAME, edu.emory.cci.pais.model.Equipment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Field }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Field")
    public JAXBElement<edu.emory.cci.pais.model.Field> createField(edu.emory.cci.pais.model.Field value) {
        return new JAXBElement<edu.emory.cci.pais.model.Field>(_Field_QNAME, edu.emory.cci.pais.model.Field.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupURI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "MarkupURI")
    public JAXBElement<MarkupURI> createMarkupURI(MarkupURI value) {
        return new JAXBElement<MarkupURI>(_MarkupURI_QNAME, MarkupURI.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupFileReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "MarkupFileReference")
    public JAXBElement<MarkupFileReference> createMarkupFileReference(MarkupFileReference value) {
        return new JAXBElement<MarkupFileReference>(_MarkupFileReference_QNAME, MarkupFileReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rectangle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Rectangle")
    public JAXBElement<Rectangle> createRectangle(Rectangle value) {
        return new JAXBElement<Rectangle>(_Rectangle_QNAME, Rectangle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.GeometricShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "GeometricShape")
    public JAXBElement<edu.emory.cci.pais.model.GeometricShape> createGeometricShape(edu.emory.cci.pais.model.GeometricShape value) {
        return new JAXBElement<edu.emory.cci.pais.model.GeometricShape>(_GeometricShape_QNAME, edu.emory.cci.pais.model.GeometricShape.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.CalculationResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "CalculationResult")
    public JAXBElement<edu.emory.cci.pais.model.CalculationResult> createCalculationResult(edu.emory.cci.pais.model.CalculationResult value) {
        return new JAXBElement<edu.emory.cci.pais.model.CalculationResult>(_CalculationResult_QNAME, edu.emory.cci.pais.model.CalculationResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.MarkupReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "MarkupReference")
    public JAXBElement<edu.emory.cci.pais.model.MarkupReference> createMarkupReference(edu.emory.cci.pais.model.MarkupReference value) {
        return new JAXBElement<edu.emory.cci.pais.model.MarkupReference>(_MarkupReference_QNAME, edu.emory.cci.pais.model.MarkupReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Point }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Point")
    public JAXBElement<Point> createPoint(Point value) {
        return new JAXBElement<Point>(_Point_QNAME, Point.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Group")
    public JAXBElement<edu.emory.cci.pais.model.Group> createGroup(edu.emory.cci.pais.model.Group value) {
        return new JAXBElement<edu.emory.cci.pais.model.Group>(_Group_QNAME, edu.emory.cci.pais.model.Group.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Provenance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Provenance")
    public JAXBElement<edu.emory.cci.pais.model.Provenance> createProvenance(edu.emory.cci.pais.model.Provenance value) {
        return new JAXBElement<edu.emory.cci.pais.model.Provenance>(_Provenance_QNAME, edu.emory.cci.pais.model.Provenance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link edu.emory.cci.pais.model.Annotation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Annotation")
    public JAXBElement<edu.emory.cci.pais.model.Annotation> createAnnotation(edu.emory.cci.pais.model.Annotation value) {
        return new JAXBElement<edu.emory.cci.pais.model.Annotation>(_Annotation_QNAME, edu.emory.cci.pais.model.Annotation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageSeries }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "ImageSeries")
    public JAXBElement<ImageSeries> createImageSeries(ImageSeries value) {
        return new JAXBElement<ImageSeries>(_ImageSeries_QNAME, ImageSeries.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ratio }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gme://caCORE.caCORE/3.2/edu.emory.cci.pais", name = "Ratio")
    public JAXBElement<Ratio> createRatio(Ratio value) {
        return new JAXBElement<Ratio>(_Ratio_QNAME, Ratio.class, null, value);
    }

}
