package edu.emory.cci.imagedb.ModelBeans;

// Generated Jul 6, 2011 7:35:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Activitystatus generated by hbm2java
 */
public class Activitystatus implements java.io.Serializable {

	private long id;
	private String status;
	private String description;
	private Set<Image> images = new HashSet<Image>(0);

	public Activitystatus() {
	}

	public Activitystatus(long id) {
		this.id = id;
	}

	public Activitystatus(long id, String status, String description,
			Set<Image> images) {
		this.id = id;
		this.status = status;
		this.description = description;
		this.images = images;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
