package edu.emory.cci.imagedb.ModelBeans;

// Generated Jul 6, 2011 7:35:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Experimenter generated by hbm2java
 */
public class Experimenter implements java.io.Serializable {

	private long id;
	private Integer version;
	private Long permissions;
	private String email;
	private String firstname;
	private String institution;
	private String lastname;
	private String middlename;
	private String omename;
	private Long externalId;
	private String userUid;
	private String loginname;
	private String name;
	private Set<Experimentergroup> experimentergroups = new HashSet<Experimentergroup>(
			0);
	private Set<Experimentalstudy> experimentalstudies = new HashSet<Experimentalstudy>(
			0);

	public Experimenter() {
	}

	public Experimenter(long id) {
		this.id = id;
	}

	public Experimenter(long id, Long permissions, String email,
			String firstname, String institution, String lastname,
			String middlename, String omename, Long externalId, String userUid,
			String loginname, String name,
			Set<Experimentergroup> experimentergroups,
			Set<Experimentalstudy> experimentalstudies) {
		this.id = id;
		this.permissions = permissions;
		this.email = email;
		this.firstname = firstname;
		this.institution = institution;
		this.lastname = lastname;
		this.middlename = middlename;
		this.omename = omename;
		this.externalId = externalId;
		this.userUid = userUid;
		this.loginname = loginname;
		this.name = name;
		this.experimentergroups = experimentergroups;
		this.experimentalstudies = experimentalstudies;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Long getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Long permissions) {
		this.permissions = permissions;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	public String getOmename() {
		return this.omename;
	}

	public void setOmename(String omename) {
		this.omename = omename;
	}

	public Long getExternalId() {
		return this.externalId;
	}

	public void setExternalId(Long externalId) {
		this.externalId = externalId;
	}

	public String getUserUid() {
		return this.userUid;
	}

	public void setUserUid(String userUid) {
		this.userUid = userUid;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Experimentergroup> getExperimentergroups() {
		return this.experimentergroups;
	}

	public void setExperimentergroups(Set<Experimentergroup> experimentergroups) {
		this.experimentergroups = experimentergroups;
	}

	public Set<Experimentalstudy> getExperimentalstudies() {
		return this.experimentalstudies;
	}

	public void setExperimentalstudies(
			Set<Experimentalstudy> experimentalstudies) {
		this.experimentalstudies = experimentalstudies;
	}

}
