package edu.emory.cci.imagedb.ModelBeans;

// Generated Jul 6, 2011 7:35:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Experimentergroup generated by hbm2java
 */
public class Experimentergroup implements java.io.Serializable {

	private long id;
	private Integer version;
	private String description;
	private String permissions;
	private String name;
	private Long externalId;
	private String groupUid;
	private String uri;
	private Set<Experimenter> experimenters = new HashSet<Experimenter>(0);

	public Experimentergroup() {
	}

	public Experimentergroup(long id) {
		this.id = id;
	}

	public Experimentergroup(long id, String description, String permissions,
			String name, Long externalId, String groupUid, String uri,
			Set<Experimenter> experimenters) {
		this.id = id;
		this.description = description;
		this.permissions = permissions;
		this.name = name;
		this.externalId = externalId;
		this.groupUid = groupUid;
		this.uri = uri;
		this.experimenters = experimenters;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPermissions() {
		return this.permissions;
	}

	public void setPermissions(String permissions) {
		this.permissions = permissions;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getExternalId() {
		return this.externalId;
	}

	public void setExternalId(Long externalId) {
		this.externalId = externalId;
	}

	public String getGroupUid() {
		return this.groupUid;
	}

	public void setGroupUid(String groupUid) {
		this.groupUid = groupUid;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public Set<Experimenter> getExperimenters() {
		return this.experimenters;
	}

	public void setExperimenters(Set<Experimenter> experimenters) {
		this.experimenters = experimenters;
	}

}
