package edu.emory.cci.imagedb.ModelBeans;

// Generated Jul 6, 2011 7:35:37 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigInteger;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	private long id;
	private Integer version;
	private Instrument instrument;
	private Location location;
	private Dataset dataset;
	private Patient patient;
	private Specimen specimen;
	private Date acquisitiondate;
	private Character archived;
	private String description;
	private Long permissions;
	private String name;
	private Character partial;
	private Long experiment;
	private Long format;
	private Long imagingenvironment;
	private Long objectivesettings;
	private Long stagelebel;
	private Long creationId;
	private Long externalId;
	private Long groupId;
	private Long ownerId;
	private Long updateId;
	private Long filesize;
	private String resolution;
	private String imagereferenceUid;
	private Blob thumbnail;
	private Blob bigThumbnail;
	private int width;
	private int height;
	private Set<Activitystatus> activitystatuses = new HashSet<Activitystatus>(
			0);
	private Set<Tileset> tileset = new HashSet<Tileset>(0);

	public Image() {
	}

	public Image(long id) {
		this.id = id;
	}

	

	public Image(long id, Integer version, Instrument instrument,
			Location location, Dataset dataset, Patient patient,
			Specimen specimen, Date acquisitiondate, Character archived,
			String description, Long permissions, String name,
			Character partial, Long experiment, Long format,
			Long imagingenvironment, Long objectivesettings, Long stagelebel,
			Long creationId, Long externalId, Long groupId, Long ownerId,
			Long updateId, Long filesize, String resolution,
			String imagereferenceUid, Blob thumbnail, Blob bigThumbnail,
			int width, int height, Set<Activitystatus> activitystatuses,
			Set<Tileset> tileset) {
		super();
		this.id = id;
		this.version = version;
		this.instrument = instrument;
		this.location = location;
		this.dataset = dataset;
		this.patient = patient;
		this.specimen = specimen;
		this.acquisitiondate = acquisitiondate;
		this.archived = archived;
		this.description = description;
		this.permissions = permissions;
		this.name = name;
		this.partial = partial;
		this.experiment = experiment;
		this.format = format;
		this.imagingenvironment = imagingenvironment;
		this.objectivesettings = objectivesettings;
		this.stagelebel = stagelebel;
		this.creationId = creationId;
		this.externalId = externalId;
		this.groupId = groupId;
		this.ownerId = ownerId;
		this.updateId = updateId;
		this.filesize = filesize;
		this.resolution = resolution;
		this.imagereferenceUid = imagereferenceUid;
		this.thumbnail = thumbnail;
		this.bigThumbnail = bigThumbnail;
		this.width = width;
		this.height = height;
		this.activitystatuses = activitystatuses;
		this.tileset = tileset;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Instrument getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Instrument instrument) {
		this.instrument = instrument;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public Dataset getDataset() {
		return this.dataset;
	}

	public void setDataset(Dataset dataset) {
		this.dataset = dataset;
	}

	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public Specimen getSpecimen() {
		return this.specimen;
	}

	public void setSpecimen(Specimen specimen) {
		this.specimen = specimen;
	}

	public Date getAcquisitiondate() {
		return this.acquisitiondate;
	}

	public void setAcquisitiondate(Date acquisitiondate) {
		this.acquisitiondate = acquisitiondate;
	}

	public Character getArchived() {
		return this.archived;
	}

	public void setArchived(Character archived) {
		this.archived = archived;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Long permissions) {
		this.permissions = permissions;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Character getPartial() {
		return this.partial;
	}

	public void setPartial(Character partial) {
		this.partial = partial;
	}

	public Long getExperiment() {
		return this.experiment;
	}

	public void setExperiment(Long experiment) {
		this.experiment = experiment;
	}

	public Long getFormat() {
		return this.format;
	}

	public void setFormat(Long format) {
		this.format = format;
	}

	public Long getImagingenvironment() {
		return this.imagingenvironment;
	}

	public void setImagingenvironment(Long imagingenvironment) {
		this.imagingenvironment = imagingenvironment;
	}

	public Long getObjectivesettings() {
		return this.objectivesettings;
	}

	public void setObjectivesettings(Long objectivesettings) {
		this.objectivesettings = objectivesettings;
	}

	public Long getStagelebel() {
		return this.stagelebel;
	}

	public void setStagelebel(Long stagelebel) {
		this.stagelebel = stagelebel;
	}

	public Long getCreationId() {
		return this.creationId;
	}

	public void setCreationId(Long creationId) {
		this.creationId = creationId;
	}

	public Long getExternalId() {
		return this.externalId;
	}

	public void setExternalId(Long externalId) {
		this.externalId = externalId;
	}

	public Long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	public Long getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Long ownerId) {
		this.ownerId = ownerId;
	}

	public Long getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(Long updateId) {
		this.updateId = updateId;
	}

	public Long getFilesize() {
		return this.filesize;
	}

	public void setFilesize(Long filesize) {
		this.filesize = filesize;
	}

	public String getResolution() {
		return this.resolution;
	}

	public void setResolution(String resolution) {
		this.resolution = resolution;
	}

	public String getImagereferenceUid() {
		return this.imagereferenceUid;
	}

	public void setImagereferenceUid(String imagereferenceUid) {
		this.imagereferenceUid = imagereferenceUid;
	}

	public Blob getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(Blob thumbnail) {
		this.thumbnail = thumbnail;
	}

	public Blob getBigThumbnail() {
		return this.bigThumbnail;
	}

	public void setBigThumbnail(Blob bigThumbnail) {
		this.bigThumbnail = bigThumbnail;
	}

	public Set<Activitystatus> getActivitystatuses() {
		return this.activitystatuses;
	}

	public void setActivitystatuses(Set<Activitystatus> activitystatuses) {
		this.activitystatuses = activitystatuses;
	}

	public Set<Tileset> getTileset() {
		return this.tileset;
	}

	public void setTileset(Set<Tileset> tileset) {
		this.tileset = tileset;
	}

	public int getWidth() {
		return width;
	}

	public void setWidth(int width) {
		this.width = width;
	}

	public int getHeight() {
		return height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

}
