package edu.emory.cci.imagedb.ModelBeans;

// Generated Jul 6, 2011 7:35:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Instrument generated by hbm2java
 */
public class Instrument implements java.io.Serializable {

	private long id;
	private Integer version;
	private Long permissions;
	private Long creationId;
	private Long externalId;
	private Long groupId;
	private Long ownerId;
	private Long updateId;
	private Long microscope;
	private String manufacturer;
	private String manufacturermodelname;
	private String softwareversion;
	private Set<Image> images = new HashSet<Image>(0);

	public Instrument() {
	}

	public Instrument(long id) {
		this.id = id;
	}

	public Instrument(long id, Long permissions, Long creationId,
			Long externalId, Long groupId, Long ownerId, Long updateId,
			Long microscope, String manufacturer, String manufacturermodelname,
			String softwareversion, Set<Image> images) {
		this.id = id;
		this.permissions = permissions;
		this.creationId = creationId;
		this.externalId = externalId;
		this.groupId = groupId;
		this.ownerId = ownerId;
		this.updateId = updateId;
		this.microscope = microscope;
		this.manufacturer = manufacturer;
		this.manufacturermodelname = manufacturermodelname;
		this.softwareversion = softwareversion;
		this.images = images;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Long getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Long permissions) {
		this.permissions = permissions;
	}

	public Long getCreationId() {
		return this.creationId;
	}

	public void setCreationId(Long creationId) {
		this.creationId = creationId;
	}

	public Long getExternalId() {
		return this.externalId;
	}

	public void setExternalId(Long externalId) {
		this.externalId = externalId;
	}

	public Long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	public Long getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Long ownerId) {
		this.ownerId = ownerId;
	}

	public Long getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(Long updateId) {
		this.updateId = updateId;
	}

	public Long getMicroscope() {
		return this.microscope;
	}

	public void setMicroscope(Long microscope) {
		this.microscope = microscope;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getManufacturermodelname() {
		return this.manufacturermodelname;
	}

	public void setManufacturermodelname(String manufacturermodelname) {
		this.manufacturermodelname = manufacturermodelname;
	}

	public String getSoftwareversion() {
		return this.softwareversion;
	}

	public void setSoftwareversion(String softwareversion) {
		this.softwareversion = softwareversion;
	}

	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
