package edu.emory.cci.imagedb.ModelBeans;

// Generated Jul 6, 2011 7:35:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private long id;
	private Integer version;
	private String description;
	private Long permissions;
	private String name;
	private Long creationId;
	private Long externalId;
	private Long groupId;
	private Long ownerId;
	private Long updateId;
	private String projectUid;
	private String uri;
	private Set<Experimentalstudy> experimentalstudies = new HashSet<Experimentalstudy>(
			0);

	public Project() {
	}

	public Project(long id) {
		this.id = id;
	}

	public Project(long id, String description, Long permissions, String name,
			Long creationId, Long externalId, Long groupId, Long ownerId,
			Long updateId, String projectUid, String uri,
			Set<Experimentalstudy> experimentalstudies) {
		this.id = id;
		this.description = description;
		this.permissions = permissions;
		this.name = name;
		this.creationId = creationId;
		this.externalId = externalId;
		this.groupId = groupId;
		this.ownerId = ownerId;
		this.updateId = updateId;
		this.projectUid = projectUid;
		this.uri = uri;
		this.experimentalstudies = experimentalstudies;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Long permissions) {
		this.permissions = permissions;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getCreationId() {
		return this.creationId;
	}

	public void setCreationId(Long creationId) {
		this.creationId = creationId;
	}

	public Long getExternalId() {
		return this.externalId;
	}

	public void setExternalId(Long externalId) {
		this.externalId = externalId;
	}

	public Long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	public Long getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Long ownerId) {
		this.ownerId = ownerId;
	}

	public Long getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(Long updateId) {
		this.updateId = updateId;
	}

	public String getProjectUid() {
		return this.projectUid;
	}

	public void setProjectUid(String projectUid) {
		this.projectUid = projectUid;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public Set<Experimentalstudy> getExperimentalstudies() {
		return this.experimentalstudies;
	}

	public void setExperimentalstudies(
			Set<Experimentalstudy> experimentalstudies) {
		this.experimentalstudies = experimentalstudies;
	}

}
