package edu.emory.cci.imagedb.ModelBeans;

// Generated Jul 6, 2011 7:35:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Specimen generated by hbm2java
 */
public class Specimen implements java.io.Serializable {

	private long id;
	private String type;
	private String stain;
	private String specimenUid;
	private String sliceId;
	private String tissueId;
	private Set<Image> images = new HashSet<Image>(0);

	public Specimen() {
	}

	public Specimen(long id) {
		this.id = id;
	}

	public Specimen(long id, String type, String stain, String specimenUid,
			String sliceId, String tissueId, Set<Image> images) {
		this.id = id;
		this.type = type;
		this.stain = stain;
		this.specimenUid = specimenUid;
		this.sliceId = sliceId;
		this.tissueId = tissueId;
		this.images = images;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStain() {
		return this.stain;
	}

	public void setStain(String stain) {
		this.stain = stain;
	}

	public String getSpecimenUid() {
		return this.specimenUid;
	}

	public void setSpecimenUid(String specimenUid) {
		this.specimenUid = specimenUid;
	}

	public String getSliceId() {
		return this.sliceId;
	}

	public void setSliceId(String sliceId) {
		this.sliceId = sliceId;
	}

	public String getTissueId() {
		return this.tissueId;
	}

	public void setTissueId(String tissueId) {
		this.tissueId = tissueId;
	}

	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
