DROP TABLE MICCAI.usermask;
DROP TABLE MICCAI.humanmask;
DROP TABLE MICCAI.classification;
DROP TABLE MICCAI.submissiontimestamp;
DROP TABLE MICCAI.maskintersection;
DROP TABLE MICCAI.maskunion;

CREATE TABLE MICCAI.usermask(
 user VARCHAR(16) NOT NULL,
 image VARCHAR(32) NOT NULL,
 x INT NOT NULL,
 y INT NOT NULL,
 PRIMARY KEY (user, image, x, y)
)
COMPRESS YES
IN SPATIALTBS32K;


CREATE TABLE MICCAI.humanmask(
 image VARCHAR(32) NOT NULL,
 x INT NOT NULL,
 y INT NOT NULL,
 PRIMARY KEY (image, x, y)
)
COMPRESS YES
IN SPATIALTBS32K;


CREATE TABLE MICCAI.classification (
 user VARCHAR(16) NOT NULL,
 image VARCHAR(32) NOT NULL,
label VARCHAR(5) NOT NULL
)
IN SPATIALTBS32K;


CREATE TABLE MICCAI.submissiontimestamp (
user VARCHAR(16) NOT NULL,
type VARCHAR(16) NOT NULL,
timestamp BIGINT NOT NULL
)
IN SPATIALTBS32K;

CREATE TABLE MICCAI.maskintersection (
user VARCHAR(16) NOT NULL,
image VARCHAR(32) NOT NULL,
intersection BIGINT NOT NULL,
PRIMARY KEY (user, image)
)
IN SPATIALTBS32K;

CREATE TABLE MICCAI.maskunion (
user VARCHAR(16) NOT NULL,
image VARCHAR(32) NOT NULL,
union BIGINT NOT NULL,
PRIMARY KEY (user, image)
)
IN SPATIALTBS32K;







