DROP TABLE PAIS.STAGINGDOC;
DROP TABLE PAIS.LOADING_LOG;
DROP TABLE PAIS.METADOC;
DROP TABLE PAIS.PAIS;
DROP TABLE PAIS.PROJECT;
DROP TABLE PAIS.GROUP;
DROP TABLE PAIS.USER;
DROP TABLE PAIS.COLLECTION;
DROP TABLE PAIS.WHOLESLIDEIMAGEREFERENCE;
DROP TABLE PAIS.REGION;
DROP TABLE PAIS.SPECIMEN;
DROP TABLE PAIS.ANATOMICENTITY;
DROP TABLE PAIS.PATIENT;

DROP TABLE PAIS.OBSERVATION_QUANTIFICATION_ORDINAL;
DROP TABLE PAIS.OBSERVATION_QUANTIFICATION_NOMINAL;
DROP TABLE PAIS.ANNOTATION_MARKUP;
DROP TABLE PAIS.MARKUP_POLYGON;
DROP TABLE PAIS.MARKUP_POLYGON_HUMAN;

DROP TABLE PAIS.PROVENANCE;
DROP TABLE PAIS.ALGORITHM;
DROP TABLE PAIS.PARAMETER;
DROP TABLE PAIS.INPUTFILEREFERENCE;

DROP TABLE PAIS.CALCULATION_FLAT;
DROP TABLE PAIS.CALCULATION_DICTIONARY;
DROP TABLE PAIS.OBSERVATION_DICTIONARY;

DROP TABLE PAIS.DLMSTATUS;
DROP TABLE PAIS.TEMPLATE;
DROP TABLE PAIS.FEATURES;
DROP TABLE PAIS.TEMPLATEFEATURESRL;

DROP TABLE PAIS.PATIENT_CHARACTERISTIC;
drop table pais.feature_covariance;
drop table pais.feature_histogram;
drop table pais.feature_aggregate;
drop table pais.mean_feature_vector;
drop table pais.temp_feature_aggregate;
drop table pais.temp_feature_covariance;


CREATE TABLE PAIS.STAGINGDOC(
	UID	 		VARCHAR(64),  
	TILENAME 		VARCHAR(64), 
	BLOB 			BLOB (1024M) NOT  LOGGED  NOT  COMPACT, 
	STATUS 			VARCHAR(24) WITH DEFAULT 'INCOMPLETE',
	INSERT_TIME		TIMESTAMP,
	COMPLETE_TIME		TIMESTAMP,
	COMPLETE_COUNT		INTEGER,
	LOADING_TIME		DECIMAL(6,2),
	FILE_NAME		VARCHAR(256),
	SEQUENCE_NUMBER		INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE), 
	LOADINGCONFIG   VARCHAR(60),
        PRIMARY KEY(SEQUENCE_NUMBER)
	) in spatialtbs32k;
	


CREATE TABLE PAIS.LOADING_LOG(
    SEQUENCE_NUMBER             INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    FAILURE_TIME 	        TIMESTAMP,
    FILE_NAME	                VARCHAR(256),
    FAILURE_MESSAGE	        VARCHAR(3000) 
)in spatialtbs32k;

--Added:
  CREATE TABLE PAIS.METADOC(
    UID                         VARCHAR(640) NOT NULL,
    XMLDOC                      XML,
    INSERTTIME                  TIMESTAMP
  )in spatialtbs32k;


  CREATE TABLE PAIS.PAIS(
    PAIS_ID			DECIMAL(30,0) NOT NULL,
    PAIS_UID			VARCHAR(64)   NOT NULL,
    NAME			VARCHAR(64),
    DATETIME			VARCHAR(64),
    PAISVERSION			VARCHAR(64),
    CODEVALUE			VARCHAR(64),  
    CODEMEANING			VARCHAR(64),
    CODINGSCHEMEDESIGNATOR	VARCHAR(64),
    CODINGSCHEMEVERSION		VARCHAR(64),  
    COMMENT			VARCHAR(128)
  );



CREATE TABLE PAIS.PROJECT(  
  PROJECT_ID 			DECIMAL(30,0) NOT NULL,
  PROJECT_UID			VARCHAR(64),
  NAME	 			VARCHAR(64),
  URI				VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL
);  


CREATE TABLE PAIS.GROUP(  
  GROUP_ID 			DECIMAL(30,0) NOT NULL,
  GROUP_UID			VARCHAR(64),
  NAME	 			VARCHAR(64),
  URI				VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL
);  


CREATE TABLE PAIS.USER(
  USER_ID			DECIMAL(30,0) NOT NULL,
  LOGINNAME			VARCHAR(64),
  NAME				VARCHAR(64),
  NUMBERWITHINROLEOFCLINICALTRIAL INTEGER,
  ROLEINTRIAL			VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL
);  



CREATE TABLE PAIS.COLLECTION(  
  COLLECTION_ID 		DECIMAL(30,0) NOT NULL,
  COLLECTION_UID		VARCHAR(64) NOT NULL,
  NAME	 			VARCHAR(64),
  ROLE				VARCHAR(64),
  METHODNAME			VARCHAR(64) NOT NULL,
  SEQUENCENUMBER		INTEGER NOT NULL,
  STUDYDATETIME	        	VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL 
);  
  
 
 

 CREATE TABLE PAIS.WHOLESLIDEIMAGEREFERENCE(
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,
  IMAGEREFERENCE_UID		VARCHAR(64),
  FILEREFERENCE			VARCHAR(64),
  URI				VARCHAR(64),
  RESOLUTION			DOUBLE,
  ZAXISRESOLUTION		DOUBLE,
  ZAXISCOORDINTE		DOUBLE,
  PAIS_UID			VARCHAR(64)   NOT NULL 
);    
  


 CREATE TABLE PAIS.REGION(
  REGION_ID			DECIMAL(30,0) NOT NULL,
  NAME				VARCHAR(64) NOT NULL,
  X				DOUBLE,
  Y				DOUBLE,
  HEIGHT			DOUBLE,
  WIDTH				DOUBLE,
  ZOOMRESOLUTION		DOUBLE,
  COORDINATERESOLUTION		DOUBLE,
  COORDINATEREFERENCE		VARCHAR(64),
  POLYGON  			DB2GSE.ST_POLYGON INLINE LENGTH 512,  
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,
  PAIS_UID			VARCHAR(64)   NOT NULL
) in spatialtbs32k;   
  

 CREATE TABLE PAIS.SPECIMEN(
  SPECIMEN_ID			DECIMAL(30,0) NOT NULL,
  SPECIMEN_UID			VARCHAR(64),
  TYPE				VARCHAR(64),
  STAIN				VARCHAR(64),
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,    
  PAIS_UID			VARCHAR(64)   NOT NULL 
);    



 CREATE TABLE PAIS.ANATOMICENTITY(
  ANATOMICENTITY_ID		DECIMAL(30,0) NOT NULL,
  CODEVALUE			VARCHAR(64),  
  CODEMEANING			VARCHAR(64),
  CODINGSCHEMEDESIGNATOR	VARCHAR(64),
  CODINGSCHEMEVERSION		VARCHAR(64),
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,    
  PAIS_UID			VARCHAR(64)   NOT NULL
);   
 


CREATE TABLE PAIS.PATIENT(
  PATIENT_ID 			DECIMAL(30,0) NOT NULL,
  PATIENTID 			VARCHAR(64),  
  SEX				VARCHAR(64),  
  BIRTHDATE			VARCHAR(64),  
  ETHNICGROUP			VARCHAR(64),
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,  
  PAIS_UID			VARCHAR(64)   NOT NULL     
);


-- Removed: CALCULATION_FLAT
-- Added:
 CREATE TABLE PAIS.CALCULATION_DICTIONARY(
  DICTIONARY_ID			DECIMAL(30,0) NOT NULL, 
  METHODNAME			VARCHAR(64),
  CALCULATION_NAME		VARCHAR(64),  
  CODEVALUE			VARCHAR(64),  
  CODEMEANING			VARCHAR(64),
  CODINGSCHEMEDESIGNATOR	VARCHAR(64),
  CODINGSCHEMEVERSION		VARCHAR(64),
  DESCRIPTION			VARCHAR(512),
  DATATYPE			VARCHAR(64),
  UNITOFMEASURE			VARCHAR(64)
);

-- Added:
 CREATE TABLE PAIS.OBSERVATION_DICTIONARY(
  DICTIONARY_ID			DECIMAL(30,0) NOT NULL, 
  METHODNAME			VARCHAR(64),
  OBSERVATION_NAME		VARCHAR(64),  
  CODEVALUE			VARCHAR(64),  
  CODEMEANING			VARCHAR(64),
  CODINGSCHEMEDESIGNATOR	VARCHAR(64),
  CODINGSCHEMEVERSION		VARCHAR(64),
  DESCRIPTION			VARCHAR(512),
  DATATYPE			VARCHAR(64),
  UNITOFMEASURE			VARCHAR(64)
);


  
   CREATE TABLE PAIS.OBSERVATION_QUANTIFICATION_ORDINAL(
    OBSERVATION_ID 		DECIMAL(30,0) NOT NULL,
    OBSERVATION_NAME		VARCHAR(64),
    ANNOTATORCONFIDENCE		DOUBLE,
    
    QUANTIFICATION_ID		DECIMAL(30,0) NOT NULL,
    QUANTIFICATION_NAME		VARCHAR(64),
    QUANTIFICATION_VALUE	DOUBLE,
    QUANTIFICATION_DATATYPE	VARCHAR(64),
    PROVENANCE_ID		DECIMAL(30,0),
    MARKUP_ID			DECIMAL(30,0),

    ANNOTATION_ID		DECIMAL(30,0) NOT NULL,   
    TILENAME			VARCHAR(64) NOT NULL,    
    PAIS_UID			VARCHAR(64)   NOT NULL,    
    OBSERVATION_DICTIONARY_ID   DECIMAL(30,0)
 ) 
COMPRESS YES
IN SPATIALTBS32K;


   CREATE TABLE PAIS.OBSERVATION_QUANTIFICATION_NOMINAL(
    OBSERVATION_ID 		DECIMAL(30,0) NOT NULL,
    OBSERVATION_NAME		VARCHAR(64),
    ANNOTATORCONFIDENCE		DOUBLE,
    
    QUANTIFICATION_ID		DECIMAL(30,0) NOT NULL,
    QUANTIFICATION_NAME		VARCHAR(64),
    QUANTIFICATION_VALUE	VARCHAR(64),
    PROVENANCE_ID		DECIMAL(30,0),
    MARKUP_ID			DECIMAL(30,0),

    ANNOTATION_ID		DECIMAL(30,0) NOT NULL,   
    TILENAME			VARCHAR(64) NOT NULL,    
    PAIS_UID			VARCHAR(64)   NOT NULL,    
    OBSERVATION_DICTIONARY_ID   DECIMAL(30,0)
 ) 
COMPRESS YES
IN SPATIALTBS32K;
 
 
CREATE TABLE PAIS.ANNOTATION_MARKUP(
    ANNOTATION_ID		DECIMAL(30,0) NOT NULL,  
    MARKUP_ID			DECIMAL(30,0) NOT NULL,
    PAIS_UID			VARCHAR(64)   NOT NULL
 ) IN SPATIALTBS32K;

CREATE TABLE PAIS.MARKUP_POLYGON  (
   MARKUP_ID			DECIMAL(30,0) NOT NULL,      
   NAME				VARCHAR(64),
   GEOMETRICSHAPE_ID		DECIMAL(30,0) NOT NULL,  
   ANNOTATION_ID		DECIMAL(30,0) NOT NULL,  
   POLYGON  			DB2GSE.ST_POLYGON INLINE LENGTH 30000,
   PROVENANCE_ID		DECIMAL(30,0),   
   TILENAME			VARCHAR(64) NOT NULL,
   PAIS_UID 			VARCHAR(64) NOT NULL,
   CENTROID_X			DOUBLE,
   CENTROID_Y			DOUBLE
) 
COMPRESS YES
IN spatialtbs32k   
;

CREATE TABLE PAIS.MARKUP_POLYGON_HUMAN  (
   MARKUP_ID			DECIMAL(30,0) NOT NULL,      
   NAME				VARCHAR(64),
   GEOMETRICSHAPE_ID		DECIMAL(30,0) NOT NULL,  
   ANNOTATION_ID		DECIMAL(30,0) NOT NULL,  
   POLYGON  			DB2GSE.ST_POLYGON,
   PROVENANCE_ID		DECIMAL(30,0),   
   TILENAME			VARCHAR(64)   NOT NULL,
   PAIS_UID 			VARCHAR(64) NOT NULL
) 
COMPRESS YES
IN spatialtbs32k;   


CREATE TABLE PAIS.PROVENANCE(
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL,    
  SCOPE				VARCHAR(64),    
  PAIS_UID 			VARCHAR(64) NOT NULL   
);


CREATE TABLE PAIS.ALGORITHM(
  ALGORITHM_ID			DECIMAL(30,0) NOT NULL,    
  NAME				VARCHAR(64),
  VERSION			VARCHAR(64),
  URI				VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL,  
  PAIS_UID 			VARCHAR(64)   NOT NULL 
);  

CREATE TABLE PAIS.PARAMETER(
  PARAMETER_ID			DECIMAL(30,0) NOT NULL,    
  NAME				VARCHAR(64),
  VALUE				VARCHAR(64),
  DATATYPE			VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL,    
  ALGORITHM_ID			DECIMAL(30,0) NOT NULL, 
  PAIS_UID 			VARCHAR(64)   NOT NULL   
);  
  

CREATE TABLE PAIS.INPUTFILEREFERENCE(
  INPUTFILEREFERENCE_ID 	DECIMAL(30,0) NOT NULL,    
  FILEREFERENCE			VARCHAR(64),
  URI				VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL, 
  ALGORITHM_ID			DECIMAL(30,0) NOT NULL,      
  PAIS_UID 			VARCHAR(64)   NOT NULL    
);


 CREATE TABLE PAIS.CALCULATION_FLAT(
  ANNOTATION_ID			DECIMAL(30,0) NOT NULL,  
  ANNOTATION_NAME		VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0),
  MARKUP_ID			DECIMAL(30,0) NOT NULL, 
  TILENAME			VARCHAR(64)   NOT NULL,
  PAIS_UID			VARCHAR(64)   NOT NULL,  
  CALCULATION_DICTIONARY_ID	DECIMAL(30,0), 

  AREA 				DOUBLE,
  PERIMETER 			DOUBLE,
  ECCENTRICITY 			DOUBLE,
  CIRCULARITY	 		DOUBLE,
  MAJOR_AXIS 			DOUBLE,
  MINOR_AXIS 			DOUBLE,  
  EXTENT_RATIO 			DOUBLE,
  MEAN_INTENSITY 		DOUBLE,
  MAX_INTENSITY  		DOUBLE,
  MIN_INTENSITY  		DOUBLE,
  STD_INTENSITY  		DOUBLE,
  ENTROPY 			DOUBLE,
  ENERGY 			DOUBLE,
  SKEWNESS 			DOUBLE,
  KURTOSIS 			DOUBLE,
  MEAN_GRADIENT_MAGNITUDE 	DOUBLE,
  STD_GRADIENT_MAGNITUDE 	DOUBLE,   
  ENTROPY_GRADIENT_MAGNITUDE 	DOUBLE,   
  ENERGY_GRADIENT_MAGNITUDE 	DOUBLE,   
  SKEWNESS_GRADIENT_MAGNITUDE 	DOUBLE, 
  KURTOSIS_GRADIENT_MAGNITUDE 	DOUBLE,   
  SUM_CANNY_PIXEL 		DOUBLE,
  MEAN_CANNY_PIXEL 		DOUBLE,
CYTO_H_MeanIntensity 		DOUBLE, 
CYTO_H_MeanMedianDifferenceIntensity DOUBLE, 
CYTO_H_MaxIntensity 		DOUBLE, 
CYTO_H_MinIntensity 		DOUBLE, 
CYTO_H_StdIntensity 		DOUBLE,
CYTO_H_Entropy 			DOUBLE, 
CYTO_H_Energy 			DOUBLE, 
CYTO_H_Skewness 		DOUBLE, 
CYTO_H_Kurtosis 		DOUBLE,
CYTO_H_MeanGradMag 		DOUBLE, 
CYTO_H_StdGradMag 		DOUBLE, 
CYTO_H_EntropyGradMag 		DOUBLE, 
CYTO_H_EnergyGradMag 		DOUBLE,
CYTO_H_SkewnessGradMag 		DOUBLE, 
CYTO_H_KurtosisGradMag 		DOUBLE, 
CYTO_H_SumCanny 		DOUBLE, 
CYTO_H_MeanCanny 		DOUBLE,
CYTO_E_MeanIntensity 		DOUBLE, 
CYTO_E_MeanMedianDifferenceIntensity DOUBLE, 
CYTO_E_MaxIntensity 		DOUBLE, 
CYTO_E_MinIntensity 		DOUBLE, 
CYTO_E_StdIntensity 		DOUBLE,
CYTO_E_Entropy 			DOUBLE, 
CYTO_E_Energy 			DOUBLE, 
CYTO_E_Skewness 		DOUBLE, 
CYTO_E_Kurtosis 		DOUBLE,
CYTO_E_MeanGradMag 		DOUBLE, 
CYTO_E_StdGradMag 		DOUBLE, 
CYTO_E_EntropyGradMag 		DOUBLE, 
CYTO_E_EnergyGradMag 		DOUBLE,
CYTO_E_SkewnessGradMag 		DOUBLE, 
CYTO_E_KurtosisGradMag		 DOUBLE, 
CYTO_E_SumCanny 		DOUBLE, 
CYTO_E_MeanCanny 		DOUBLE,
CYTO_G_MeanIntensity		DOUBLE, 
CYTO_G_MeanMedianDifferenceIntensity DOUBLE, 
CYTO_G_MaxIntensity 		DOUBLE, 
CYTO_G_MinIntensity 		DOUBLE, 
CYTO_G_StdIntensity 		DOUBLE,
CYTO_G_Entropy 			DOUBLE, 
CYTO_G_Energy 			DOUBLE, 
CYTO_G_Skewness 		DOUBLE, 
CYTO_G_Kurtosis 		DOUBLE,
CYTO_G_MeanGradMag 		DOUBLE, 
CYTO_G_StdGradMag 		DOUBLE, 
CYTO_G_EntropyGradMag 		DOUBLE, 
CYTO_G_EnergyGradMag 		DOUBLE,
CYTO_G_SkewnessGradMag 		DOUBLE, 
CYTO_G_KurtosisGradMag 		DOUBLE, 
CYTO_G_SumCanny 		DOUBLE, 
CYTO_G_MeanCanny		DOUBLE   
 ) 
COMPRESS YES
IN SPATIALTBS32K
;

create table pais.patient_characteristic(
BCR_PATIENT_BARCODE VARCHAR(20),
ADDITIONAL_CHEMO_THERAPY VARCHAR(20),
ADDITIONAL_DRUG_THERAPY VARCHAR(20),
ADDITIONAL_HORMONE_THERAPY VARCHAR(20),
ADDITIONAL_IMMUNO_THERAPY VARCHAR(20),
ADDITIONAL_RADIATION_THERAPY VARCHAR(20),
AGE_AT_INITIAL_PATHOLOGIC_DIAGNOSIS BIGINT,
ANATOMIC_ORGAN_SUBDIVISION VARCHAR(20),
CHEMO_THERAPY VARCHAR(10),
DAYS_TO_BIRTH BIGINT,
DAYS_TO_DEATH BIGINT,
DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS BIGINT,
DAYS_TO_LAST_FOLLOWUP BIGINT,
DAYS_TO_TUMOR_PROGRESSION BIGINT,
DAYS_TO_TUMOR_RECURRENCE BIGINT,
GENDER VARCHAR(20),
HISTOLOGICAL_TYPE LONG VARCHAR,
HORMONAL_THERAPY VARCHAR(20),
IMMUNO_THERAPY VARCHAR(20),
INFORMED_CONSENT_VERIFIED VARCHAR(20),
INITIAL_PATHOLOGIC_DIAGNOSIS_METHOD LONG VARCHAR,
PERSON_NEOPLASM_CANCER_STATUS VARCHAR(20),
PRETREATMENT_HISTORY VARCHAR(20),
PRIOR_GLIOMA VARCHAR(20),
RADIATION_THERAPY VARCHAR(20),
TARGETED_MOLECULAR_THERAPY VARCHAR(20),
TUMOR_TISSUE_SITE LONG VARCHAR,
VITAL_STATUS VARCHAR(20),
CPATIENTID VARCHAR(10)

);






CREATE TABLE PAIS.TEMPLATE(
   TEMPLATENAME    VARCHAR(100) NOT NULL UNIQUE,
   LOADINGCONFIG XML,
   DESCRIPTION VARCHAR(1000),
   LASTSELECTTIME TIMESTAMP
);
CREATE TABLE PAIS.FEATURES(
FEATURENAME VARCHAR(100) NOT NULL UNIQUE,
DESCRIPTION VARCHAR(1000),
TYPE VARCHAR(30) NOT NULL
);

CREATE TABLE PAIS.TEMPLATEFEATURESRL(
FEATURENAME VARCHAR(100) NOT NULL,
TEMPLATENAME VARCHAR(100) NOT NULL
);

CREATE TABLE PAIS.DLMSTATUS(
   WORKSTATUS INTEGER,
   LASTHEARTBEAT TIMESTAMP
);

INSERT INTO PAIS.DLMSTATUS VALUES(1,CURRENT_TIMESTAMP);

INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('AREA','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('PERIMETER','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('ECCENTRICITY','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CIRCULARITY','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('MAJOR_AXIS','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('MINOR_AXIS','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('EXTENT_RATIO','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('MEAN_INTENSITY','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('MAX_INTENSITY','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('MIN_INTENSITY','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('STD_INTENSITY','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('ENTROPY','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('ENERGY','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('SKEWNESS','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('KURTOSIS','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('MEAN_GRADIENT_MAGNITUDE','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('STD_GRADIENT_MAGNITUDE','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('ENTROPY_GRADIENT_MAGNITUDE','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('ENERGY_GRADIENT_MAGNITUDE','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('SKEWNESS_GRADIENT_MAGNITUDE','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('KURTOSIS_GRADIENT_MAGNITUDE','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('SUM_CANNY_PIXEL','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('MEAN_CANNY_PIXEL','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_MeanIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_MeanMedianDifferenceIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_MaxIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_MinIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_StdIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_Entropy','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_Energy','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_Skewness','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_Kurtosis','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_MeanGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_StdGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_EntropyGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_EnergyGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_SkewnessGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_KurtosisGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_SumCanny','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_H_MeanCanny','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_MeanIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_MeanMedianDifferenceIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_MaxIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_MinIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_StdIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_Entropy','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_Energy','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_Skewness','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_Kurtosis','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_MeanGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_StdGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_EntropyGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_EnergyGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_SkewnessGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_KurtosisGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_SumCanny','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_E_MeanCanny','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_MeanIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_MeanMedianDifferenceIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_MaxIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_MinIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_StdIntensity','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_Entropy','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_Energy','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_Skewness','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_Kurtosis','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_MeanGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_StdGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_EntropyGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_EnergyGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_SkewnessGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_KurtosisGradMag','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_SumCanny','DOUBLE');
INSERT INTO PAIS.FEATURES(FEATURENAME,TYPE) VALUES('CYTO_G_MeanCanny','DOUBLE');
  

CREATE TABLE pais.feature_covariance( 
	 pais_uid VARCHAR(64),
	 feature VARCHAR(64),
	 area	 DOUBLE, 
	 perimeter	 DOUBLE, 
	 eccentricity	 DOUBLE, 
	 circularity	 DOUBLE, 
	 major_axis	 DOUBLE, 
	 minor_axis	 DOUBLE, 
	 extent_ratio	 DOUBLE, 
	 mean_intensity	 DOUBLE, 
	 max_intensity 	 DOUBLE, 
	 min_intensity 	 DOUBLE, 
	 std_intensity 	 DOUBLE, 
	 entropy	 DOUBLE, 
	 energy	 DOUBLE, 
	 skewness	 DOUBLE, 
	 kurtosis	 DOUBLE, 
	 mean_gradient_magnitude	 DOUBLE, 
	 std_gradient_magnitude	 DOUBLE, 
	 entropy_gradient_magnitude	 DOUBLE, 
	 energy_gradient_magnitude	 DOUBLE, 
	 skewness_gradient_magnitude	 DOUBLE, 
	 kurtosis_gradient_magnitude	 DOUBLE, 
	 sum_canny_pixel	 DOUBLE, 
	 mean_canny_pixel	 DOUBLE, 
	 cyto_h_meanintensity	 DOUBLE, 
	 cyto_h_meanmediandifferenceintensity	 DOUBLE, 
	 cyto_h_maxintensity	 DOUBLE, 
	 cyto_h_minintensity	 DOUBLE, 
	 cyto_h_stdintensity	 DOUBLE, 
	 cyto_h_entropy	 DOUBLE, 
	 cyto_h_energy	 DOUBLE, 
	 cyto_h_skewness	 DOUBLE, 
	 cyto_h_kurtosis	 DOUBLE, 
	 cyto_h_meangradmag	 DOUBLE, 
	 cyto_h_stdgradmag	 DOUBLE, 
	 cyto_h_entropygradmag	 DOUBLE, 
	 cyto_h_energygradmag	 DOUBLE, 
	 cyto_h_skewnessgradmag	 DOUBLE, 
	 cyto_h_kurtosisgradmag	 DOUBLE, 
	 cyto_h_sumcanny	 DOUBLE, 
	 cyto_h_meancanny	 DOUBLE, 
	 cyto_e_meanintensity	 DOUBLE, 
	 cyto_e_meanmediandifferenceintensity	 DOUBLE, 
	 cyto_e_maxintensity	 DOUBLE, 
	 cyto_e_minintensity	 DOUBLE, 
	 cyto_e_stdintensity	 DOUBLE, 
	 cyto_e_entropy	 DOUBLE, 
	 cyto_e_energy	 DOUBLE, 
	 cyto_e_skewness	 DOUBLE, 
	 cyto_e_kurtosis	 DOUBLE, 
	 cyto_e_meangradmag	 DOUBLE, 
	 cyto_e_stdgradmag	 DOUBLE, 
	 cyto_e_entropygradmag	 DOUBLE, 
	 cyto_e_energygradmag	 DOUBLE, 
	 cyto_e_skewnessgradmag	 DOUBLE, 
	 cyto_e_kurtosisgradmag	 DOUBLE, 
	 cyto_e_sumcanny	 DOUBLE, 
	 cyto_e_meancanny	 DOUBLE, 
	 cyto_g_meanintensity	 DOUBLE, 
	 cyto_g_meanmediandifferenceintensity	 DOUBLE, 
	 cyto_g_maxintensity	 DOUBLE, 
	 cyto_g_minintensity	 DOUBLE, 
	 cyto_g_stdintensity	 DOUBLE, 
	 cyto_g_entropy	 DOUBLE, 
	 cyto_g_energy	 DOUBLE, 
	 cyto_g_skewness	 DOUBLE, 
	 cyto_g_kurtosis	 DOUBLE, 
	 cyto_g_meangradmag	 DOUBLE, 
	 cyto_g_stdgradmag	 DOUBLE, 
	 cyto_g_entropygradmag	 DOUBLE, 
	 cyto_g_energygradmag	 DOUBLE, 
	 cyto_g_skewnessgradmag	 DOUBLE, 
	 cyto_g_kurtosisgradmag	 DOUBLE, 
	 cyto_g_sumcanny	 DOUBLE, 
	 cyto_g_meancanny	 DOUBLE
); 

CREATE TABLE  pais.feature_aggregate(
  pais_uid VARCHAR(64),
  feature VARCHAR(64),
  min double, 
  max double, 
  avg double,
  stddev double
);
create table pais.feature_histogram(
  pais_uid VARCHAR(64),
  feature VARCHAR(64),
  set_id int,
  binnum int,
  frequency bigint,
  binstart double,
  binend double);

CREATE TABLE pais.mean_feature_vector( 
	 pais_uid VARCHAR(64),
	 avg_area	 DOUBLE, 
	 avg_perimeter	 DOUBLE, 
	 avg_eccentricity	 DOUBLE, 
	 avg_circularity	 DOUBLE, 
	 avg_major_axis	 DOUBLE, 
	 avg_minor_axis	 DOUBLE, 
	 avg_extent_ratio	 DOUBLE, 
	 avg_mean_intensity	 DOUBLE, 
	 avg_max_intensity 	 DOUBLE, 
	 avg_min_intensity 	 DOUBLE, 
	 avg_std_intensity 	 DOUBLE, 
	 avg_entropy	 DOUBLE, 
	 avg_energy	 DOUBLE, 
	 avg_skewness	 DOUBLE, 
	 avg_kurtosis	 DOUBLE, 
	 avg_mean_gradient_magnitude	 DOUBLE, 
	 avg_std_gradient_magnitude	 DOUBLE, 
	 avg_entropy_gradient_magnitude	 DOUBLE, 
	 avg_energy_gradient_magnitude	 DOUBLE, 
	 avg_skewness_gradient_magnitude	 DOUBLE, 
	 avg_kurtosis_gradient_magnitude	 DOUBLE, 
	 avg_sum_canny_pixel	 DOUBLE, 
	 avg_mean_canny_pixel	 DOUBLE, 
	 avg_cyto_h_meanintensity	 DOUBLE, 
	 avg_cyto_h_meanmediandifferenceintensity	 DOUBLE, 
	 avg_cyto_h_maxintensity	 DOUBLE, 
	 avg_cyto_h_minintensity	 DOUBLE, 
	 avg_cyto_h_stdintensity	 DOUBLE, 
	 avg_cyto_h_entropy	 DOUBLE, 
	 avg_cyto_h_energy	 DOUBLE, 
	 avg_cyto_h_skewness	 DOUBLE, 
	 avg_cyto_h_kurtosis	 DOUBLE, 
	 avg_cyto_h_meangradmag	 DOUBLE, 
	 avg_cyto_h_stdgradmag	 DOUBLE, 
	 avg_cyto_h_entropygradmag	 DOUBLE, 
	 avg_cyto_h_energygradmag	 DOUBLE, 
	 avg_cyto_h_skewnessgradmag	 DOUBLE, 
	 avg_cyto_h_kurtosisgradmag	 DOUBLE, 
	 avg_cyto_h_sumcanny	 DOUBLE, 
	 avg_cyto_h_meancanny	 DOUBLE, 
	 avg_cyto_e_meanintensity	 DOUBLE, 
	 avg_cyto_e_meanmediandifferenceintensity	 DOUBLE, 
	 avg_cyto_e_maxintensity	 DOUBLE, 
	 avg_cyto_e_minintensity	 DOUBLE, 
	 avg_cyto_e_stdintensity	 DOUBLE, 
	 avg_cyto_e_entropy	 DOUBLE, 
	 avg_cyto_e_energy	 DOUBLE, 
	 avg_cyto_e_skewness	 DOUBLE, 
	 avg_cyto_e_kurtosis	 DOUBLE, 
	 avg_cyto_e_meangradmag	 DOUBLE, 
	 avg_cyto_e_stdgradmag	 DOUBLE, 
	 avg_cyto_e_entropygradmag	 DOUBLE, 
	 avg_cyto_e_energygradmag	 DOUBLE, 
	 avg_cyto_e_skewnessgradmag	 DOUBLE, 
	 avg_cyto_e_kurtosisgradmag	 DOUBLE, 
	 avg_cyto_e_sumcanny	 DOUBLE, 
	 avg_cyto_e_meancanny	 DOUBLE, 
	 avg_cyto_g_meanintensity	 DOUBLE, 
	 avg_cyto_g_meanmediandifferenceintensity	 DOUBLE, 
	 avg_cyto_g_maxintensity	 DOUBLE, 
	 avg_cyto_g_minintensity	 DOUBLE, 
	 avg_cyto_g_stdintensity	 DOUBLE, 
	 avg_cyto_g_entropy	 DOUBLE, 
	 avg_cyto_g_energy	 DOUBLE, 
	 avg_cyto_g_skewness	 DOUBLE, 
	 avg_cyto_g_kurtosis	 DOUBLE, 
	 avg_cyto_g_meangradmag	 DOUBLE, 
	 avg_cyto_g_stdgradmag	 DOUBLE, 
	 avg_cyto_g_entropygradmag	 DOUBLE, 
	 avg_cyto_g_energygradmag	 DOUBLE, 
	 avg_cyto_g_skewnessgradmag	 DOUBLE, 
	 avg_cyto_g_kurtosisgradmag	 DOUBLE, 
	 avg_cyto_g_sumcanny	 DOUBLE, 
	 avg_cyto_g_meancanny	 DOUBLE,
         std_area	 DOUBLE, 
	 std_perimeter	 DOUBLE, 
	 std_eccentricity	 DOUBLE, 
	 std_circularity	 DOUBLE, 
	 std_major_axis	 DOUBLE, 
	 std_minor_axis	 DOUBLE, 
	 std_extent_ratio	 DOUBLE, 
	 std_mean_intensity	 DOUBLE, 
	 std_max_intensity 	 DOUBLE, 
	 std_min_intensity 	 DOUBLE, 
	 std_std_intensity 	 DOUBLE, 
	 std_entropy	 DOUBLE, 
	 std_energy	 DOUBLE, 
	 std_skewness	 DOUBLE, 
	 std_kurtosis	 DOUBLE, 
	 std_mean_gradient_magnitude	 DOUBLE, 
	 std_std_gradient_magnitude	 DOUBLE, 
	 std_entropy_gradient_magnitude	 DOUBLE, 
	 std_energy_gradient_magnitude	 DOUBLE, 
	 std_skewness_gradient_magnitude	 DOUBLE, 
	 std_kurtosis_gradient_magnitude	 DOUBLE, 
	 std_sum_canny_pixel	 DOUBLE, 
	 std_mean_canny_pixel	 DOUBLE, 
	 std_cyto_h_meanintensity	 DOUBLE, 
	 std_cyto_h_meanmediandifferenceintensity	 DOUBLE, 
	 std_cyto_h_maxintensity	 DOUBLE, 
	 std_cyto_h_minintensity	 DOUBLE, 
	 std_cyto_h_stdintensity	 DOUBLE, 
	 std_cyto_h_entropy	 DOUBLE, 
	 std_cyto_h_energy	 DOUBLE, 
	 std_cyto_h_skewness	 DOUBLE, 
	 std_cyto_h_kurtosis	 DOUBLE, 
	 std_cyto_h_meangradmag	 DOUBLE, 
	 std_cyto_h_stdgradmag	 DOUBLE, 
	 std_cyto_h_entropygradmag	 DOUBLE, 
	 std_cyto_h_energygradmag	 DOUBLE, 
	 std_cyto_h_skewnessgradmag	 DOUBLE, 
	 std_cyto_h_kurtosisgradmag	 DOUBLE, 
	 std_cyto_h_sumcanny	 DOUBLE, 
	 std_cyto_h_meancanny	 DOUBLE, 
	 std_cyto_e_meanintensity	 DOUBLE, 
	 std_cyto_e_meanmediandifferenceintensity	 DOUBLE, 
	 std_cyto_e_maxintensity	 DOUBLE, 
	 std_cyto_e_minintensity	 DOUBLE, 
	 std_cyto_e_stdintensity	 DOUBLE, 
	 std_cyto_e_entropy	 DOUBLE, 
	 std_cyto_e_energy	 DOUBLE, 
	 std_cyto_e_skewness	 DOUBLE, 
	 std_cyto_e_kurtosis	 DOUBLE, 
	 std_cyto_e_meangradmag	 DOUBLE, 
	 std_cyto_e_stdgradmag	 DOUBLE, 
	 std_cyto_e_entropygradmag	 DOUBLE, 
	 std_cyto_e_energygradmag	 DOUBLE, 
	 std_cyto_e_skewnessgradmag	 DOUBLE, 
	 std_cyto_e_kurtosisgradmag	 DOUBLE, 
	 std_cyto_e_sumcanny	 DOUBLE, 
	 std_cyto_e_meancanny	 DOUBLE, 
	 std_cyto_g_meanintensity	 DOUBLE, 
	 std_cyto_g_meanmediandifferenceintensity	 DOUBLE, 
	 std_cyto_g_maxintensity	 DOUBLE, 
	 std_cyto_g_minintensity	 DOUBLE, 
	 std_cyto_g_stdintensity	 DOUBLE, 
	 std_cyto_g_entropy	 DOUBLE, 
	 std_cyto_g_energy	 DOUBLE, 
	 std_cyto_g_skewness	 DOUBLE, 
	 std_cyto_g_kurtosis	 DOUBLE, 
	 std_cyto_g_meangradmag	 DOUBLE, 
	 std_cyto_g_stdgradmag	 DOUBLE, 
	 std_cyto_g_entropygradmag	 DOUBLE, 
	 std_cyto_g_energygradmag	 DOUBLE, 
	 std_cyto_g_skewnessgradmag	 DOUBLE, 
	 std_cyto_g_kurtosisgradmag	 DOUBLE, 
	 std_cyto_g_sumcanny	 DOUBLE, 
	 std_cyto_g_meancanny	 DOUBLE); 

CREATE TABLE pais.temp_feature_aggregate( 
	 pais_uid VARCHAR(64),
	 avg_area	 DOUBLE, 
	 min_area	 DOUBLE, 
	 max_area	 DOUBLE, 
	 stddev_area	 DOUBLE, 
	 avg_perimeter	 DOUBLE, 
	 min_perimeter	 DOUBLE, 
	 max_perimeter	 DOUBLE, 
	 stddev_perimeter	 DOUBLE, 
	 avg_eccentricity	 DOUBLE, 
	 min_eccentricity	 DOUBLE, 
	 max_eccentricity	 DOUBLE, 
	 stddev_eccentricity	 DOUBLE, 
	 avg_circularity	 DOUBLE, 
	 min_circularity	 DOUBLE, 
	 max_circularity	 DOUBLE, 
	 stddev_circularity	 DOUBLE, 
	 avg_major_axis	 DOUBLE, 
	 min_major_axis	 DOUBLE, 
	 max_major_axis	 DOUBLE, 
	 stddev_major_axis	 DOUBLE, 
	 avg_minor_axis	 DOUBLE, 
	 min_minor_axis	 DOUBLE, 
	 max_minor_axis	 DOUBLE, 
	 stddev_minor_axis	 DOUBLE, 
	 avg_extent_ratio	 DOUBLE, 
	 min_extent_ratio	 DOUBLE, 
	 max_extent_ratio	 DOUBLE, 
	 stddev_extent_ratio	 DOUBLE, 
	 avg_mean_intensity	 DOUBLE, 
	 min_mean_intensity	 DOUBLE, 
	 max_mean_intensity	 DOUBLE, 
	 stddev_mean_intensity	 DOUBLE, 
	 avg_max_intensity	 DOUBLE, 
	 min_max_intensity	 DOUBLE, 
	 max_max_intensity	 DOUBLE, 
	 stddev_max_intensity	 DOUBLE, 
	 avg_min_intensity	 DOUBLE, 
	 min_min_intensity	 DOUBLE, 
	 max_min_intensity	 DOUBLE, 
	 stddev_min_intensity	 DOUBLE, 
	 avg_std_intensity	 DOUBLE, 
	 min_std_intensity	 DOUBLE, 
	 max_std_intensity	 DOUBLE, 
	 stddev_std_intensity	 DOUBLE, 
	 avg_entropy	 DOUBLE, 
	 min_entropy	 DOUBLE, 
	 max_entropy	 DOUBLE, 
	 stddev_entropy	 DOUBLE, 
	 avg_energy	 DOUBLE, 
	 min_energy	 DOUBLE, 
	 max_energy	 DOUBLE, 
	 stddev_energy	 DOUBLE, 
	 avg_skewness	 DOUBLE, 
	 min_skewness	 DOUBLE, 
	 max_skewness	 DOUBLE, 
	 stddev_skewness	 DOUBLE, 
	 avg_kurtosis	 DOUBLE, 
	 min_kurtosis	 DOUBLE, 
	 max_kurtosis	 DOUBLE, 
	 stddev_kurtosis	 DOUBLE, 
	 avg_mean_gradient_magnitude	 DOUBLE, 
	 min_mean_gradient_magnitude	 DOUBLE, 
	 max_mean_gradient_magnitude	 DOUBLE, 
	 stddev_mean_gradient_magnitude	 DOUBLE, 
	 avg_std_gradient_magnitude	 DOUBLE, 
	 min_std_gradient_magnitude	 DOUBLE, 
	 max_std_gradient_magnitude	 DOUBLE, 
	 stddev_std_gradient_magnitude	 DOUBLE, 
	 avg_entropy_gradient_magnitude	 DOUBLE, 
	 min_entropy_gradient_magnitude	 DOUBLE, 
	 max_entropy_gradient_magnitude	 DOUBLE, 
	 stddev_entropy_gradient_magnitude	 DOUBLE, 
	 avg_energy_gradient_magnitude	 DOUBLE, 
	 min_energy_gradient_magnitude	 DOUBLE, 
	 max_energy_gradient_magnitude	 DOUBLE, 
	 stddev_energy_gradient_magnitude	 DOUBLE, 
	 avg_skewness_gradient_magnitude	 DOUBLE, 
	 min_skewness_gradient_magnitude	 DOUBLE, 
	 max_skewness_gradient_magnitude	 DOUBLE, 
	 stddev_skewness_gradient_magnitude	 DOUBLE, 
	 avg_kurtosis_gradient_magnitude	 DOUBLE, 
	 min_kurtosis_gradient_magnitude	 DOUBLE, 
	 max_kurtosis_gradient_magnitude	 DOUBLE, 
	 stddev_kurtosis_gradient_magnitude	 DOUBLE, 
	 avg_sum_canny_pixel	 DOUBLE, 
	 min_sum_canny_pixel	 DOUBLE, 
	 max_sum_canny_pixel	 DOUBLE, 
	 stddev_sum_canny_pixel	 DOUBLE, 
	 avg_mean_canny_pixel	 DOUBLE, 
	 min_mean_canny_pixel	 DOUBLE, 
	 max_mean_canny_pixel	 DOUBLE, 
	 stddev_mean_canny_pixel	 DOUBLE, 
	 avg_cyto_h_meanintensity	 DOUBLE, 
	 min_cyto_h_meanintensity	 DOUBLE, 
	 max_cyto_h_meanintensity	 DOUBLE, 
	 stddev_cyto_h_meanintensity	 DOUBLE, 
	 avg_cyto_h_meanmediandifferenceintensity	 DOUBLE, 
	 min_cyto_h_meanmediandifferenceintensity	 DOUBLE, 
	 max_cyto_h_meanmediandifferenceintensity	 DOUBLE, 
	 stddev_cyto_h_meanmediandifferenceintensity	 DOUBLE, 
	 avg_cyto_h_maxintensity	 DOUBLE, 
	 min_cyto_h_maxintensity	 DOUBLE, 
	 max_cyto_h_maxintensity	 DOUBLE, 
	 stddev_cyto_h_maxintensity	 DOUBLE, 
	 avg_cyto_h_minintensity	 DOUBLE, 
	 min_cyto_h_minintensity	 DOUBLE, 
	 max_cyto_h_minintensity	 DOUBLE, 
	 stddev_cyto_h_minintensity	 DOUBLE, 
	 avg_cyto_h_stdintensity	 DOUBLE, 
	 min_cyto_h_stdintensity	 DOUBLE, 
	 max_cyto_h_stdintensity	 DOUBLE, 
	 stddev_cyto_h_stdintensity	 DOUBLE, 
	 avg_cyto_h_entropy	 DOUBLE, 
	 min_cyto_h_entropy	 DOUBLE, 
	 max_cyto_h_entropy	 DOUBLE, 
	 stddev_cyto_h_entropy	 DOUBLE, 
	 avg_cyto_h_energy	 DOUBLE, 
	 min_cyto_h_energy	 DOUBLE, 
	 max_cyto_h_energy	 DOUBLE, 
	 stddev_cyto_h_energy	 DOUBLE, 
	 avg_cyto_h_skewness	 DOUBLE, 
	 min_cyto_h_skewness	 DOUBLE, 
	 max_cyto_h_skewness	 DOUBLE, 
	 stddev_cyto_h_skewness	 DOUBLE, 
	 avg_cyto_h_kurtosis	 DOUBLE, 
	 min_cyto_h_kurtosis	 DOUBLE, 
	 max_cyto_h_kurtosis	 DOUBLE, 
	 stddev_cyto_h_kurtosis	 DOUBLE, 
	 avg_cyto_h_meangradmag	 DOUBLE, 
	 min_cyto_h_meangradmag	 DOUBLE, 
	 max_cyto_h_meangradmag	 DOUBLE, 
	 stddev_cyto_h_meangradmag	 DOUBLE, 
	 avg_cyto_h_stdgradmag	 DOUBLE, 
	 min_cyto_h_stdgradmag	 DOUBLE, 
	 max_cyto_h_stdgradmag	 DOUBLE, 
	 stddev_cyto_h_stdgradmag	 DOUBLE, 
	 avg_cyto_h_entropygradmag	 DOUBLE, 
	 min_cyto_h_entropygradmag	 DOUBLE, 
	 max_cyto_h_entropygradmag	 DOUBLE, 
	 stddev_cyto_h_entropygradmag	 DOUBLE, 
	 avg_cyto_h_energygradmag	 DOUBLE, 
	 min_cyto_h_energygradmag	 DOUBLE, 
	 max_cyto_h_energygradmag	 DOUBLE, 
	 stddev_cyto_h_energygradmag	 DOUBLE, 
	 avg_cyto_h_skewnessgradmag	 DOUBLE, 
	 min_cyto_h_skewnessgradmag	 DOUBLE, 
	 max_cyto_h_skewnessgradmag	 DOUBLE, 
	 stddev_cyto_h_skewnessgradmag	 DOUBLE, 
	 avg_cyto_h_kurtosisgradmag	 DOUBLE, 
	 min_cyto_h_kurtosisgradmag	 DOUBLE, 
	 max_cyto_h_kurtosisgradmag	 DOUBLE, 
	 stddev_cyto_h_kurtosisgradmag	 DOUBLE, 
	 avg_cyto_h_sumcanny	 DOUBLE, 
	 min_cyto_h_sumcanny	 DOUBLE, 
	 max_cyto_h_sumcanny	 DOUBLE, 
	 stddev_cyto_h_sumcanny	 DOUBLE, 
	 avg_cyto_h_meancanny	 DOUBLE, 
	 min_cyto_h_meancanny	 DOUBLE, 
	 max_cyto_h_meancanny	 DOUBLE, 
	 stddev_cyto_h_meancanny	 DOUBLE, 
	 avg_cyto_e_meanintensity	 DOUBLE, 
	 min_cyto_e_meanintensity	 DOUBLE, 
	 max_cyto_e_meanintensity	 DOUBLE, 
	 stddev_cyto_e_meanintensity	 DOUBLE, 
	 avg_cyto_e_meanmediandifferenceintensity	 DOUBLE, 
	 min_cyto_e_meanmediandifferenceintensity	 DOUBLE, 
	 max_cyto_e_meanmediandifferenceintensity	 DOUBLE, 
	 stddev_cyto_e_meanmediandifferenceintensity	 DOUBLE, 
	 avg_cyto_e_maxintensity	 DOUBLE, 
	 min_cyto_e_maxintensity	 DOUBLE, 
	 max_cyto_e_maxintensity	 DOUBLE, 
	 stddev_cyto_e_maxintensity	 DOUBLE, 
	 avg_cyto_e_minintensity	 DOUBLE, 
	 min_cyto_e_minintensity	 DOUBLE, 
	 max_cyto_e_minintensity	 DOUBLE, 
	 stddev_cyto_e_minintensity	 DOUBLE, 
	 avg_cyto_e_stdintensity	 DOUBLE, 
	 min_cyto_e_stdintensity	 DOUBLE, 
	 max_cyto_e_stdintensity	 DOUBLE, 
	 stddev_cyto_e_stdintensity	 DOUBLE, 
	 avg_cyto_e_entropy	 DOUBLE, 
	 min_cyto_e_entropy	 DOUBLE, 
	 max_cyto_e_entropy	 DOUBLE, 
	 stddev_cyto_e_entropy	 DOUBLE, 
	 avg_cyto_e_energy	 DOUBLE, 
	 min_cyto_e_energy	 DOUBLE, 
	 max_cyto_e_energy	 DOUBLE, 
	 stddev_cyto_e_energy	 DOUBLE, 
	 avg_cyto_e_skewness	 DOUBLE, 
	 min_cyto_e_skewness	 DOUBLE, 
	 max_cyto_e_skewness	 DOUBLE, 
	 stddev_cyto_e_skewness	 DOUBLE, 
	 avg_cyto_e_kurtosis	 DOUBLE, 
	 min_cyto_e_kurtosis	 DOUBLE, 
	 max_cyto_e_kurtosis	 DOUBLE, 
	 stddev_cyto_e_kurtosis	 DOUBLE, 
	 avg_cyto_e_meangradmag	 DOUBLE, 
	 min_cyto_e_meangradmag	 DOUBLE, 
	 max_cyto_e_meangradmag	 DOUBLE, 
	 stddev_cyto_e_meangradmag	 DOUBLE, 
	 avg_cyto_e_stdgradmag	 DOUBLE, 
	 min_cyto_e_stdgradmag	 DOUBLE, 
	 max_cyto_e_stdgradmag	 DOUBLE, 
	 stddev_cyto_e_stdgradmag	 DOUBLE, 
	 avg_cyto_e_entropygradmag	 DOUBLE, 
	 min_cyto_e_entropygradmag	 DOUBLE, 
	 max_cyto_e_entropygradmag	 DOUBLE, 
	 stddev_cyto_e_entropygradmag	 DOUBLE, 
	 avg_cyto_e_energygradmag	 DOUBLE, 
	 min_cyto_e_energygradmag	 DOUBLE, 
	 max_cyto_e_energygradmag	 DOUBLE, 
	 stddev_cyto_e_energygradmag	 DOUBLE, 
	 avg_cyto_e_skewnessgradmag	 DOUBLE, 
	 min_cyto_e_skewnessgradmag	 DOUBLE, 
	 max_cyto_e_skewnessgradmag	 DOUBLE, 
	 stddev_cyto_e_skewnessgradmag	 DOUBLE, 
	 avg_cyto_e_kurtosisgradmag	 DOUBLE, 
	 min_cyto_e_kurtosisgradmag	 DOUBLE, 
	 max_cyto_e_kurtosisgradmag	 DOUBLE, 
	 stddev_cyto_e_kurtosisgradmag	 DOUBLE, 
	 avg_cyto_e_sumcanny	 DOUBLE, 
	 min_cyto_e_sumcanny	 DOUBLE, 
	 max_cyto_e_sumcanny	 DOUBLE, 
	 stddev_cyto_e_sumcanny	 DOUBLE, 
	 avg_cyto_e_meancanny	 DOUBLE, 
	 min_cyto_e_meancanny	 DOUBLE, 
	 max_cyto_e_meancanny	 DOUBLE, 
	 stddev_cyto_e_meancanny	 DOUBLE, 
	 avg_cyto_g_meanintensity	 DOUBLE, 
	 min_cyto_g_meanintensity	 DOUBLE, 
	 max_cyto_g_meanintensity	 DOUBLE, 
	 stddev_cyto_g_meanintensity	 DOUBLE, 
	 avg_cyto_g_meanmediandifferenceintensity	 DOUBLE, 
	 min_cyto_g_meanmediandifferenceintensity	 DOUBLE, 
	 max_cyto_g_meanmediandifferenceintensity	 DOUBLE, 
	 stddev_cyto_g_meanmediandifferenceintensity	 DOUBLE, 
	 avg_cyto_g_maxintensity	 DOUBLE, 
	 min_cyto_g_maxintensity	 DOUBLE, 
	 max_cyto_g_maxintensity	 DOUBLE, 
	 stddev_cyto_g_maxintensity	 DOUBLE, 
	 avg_cyto_g_minintensity	 DOUBLE, 
	 min_cyto_g_minintensity	 DOUBLE, 
	 max_cyto_g_minintensity	 DOUBLE, 
	 stddev_cyto_g_minintensity	 DOUBLE, 
	 avg_cyto_g_stdintensity	 DOUBLE, 
	 min_cyto_g_stdintensity	 DOUBLE, 
	 max_cyto_g_stdintensity	 DOUBLE, 
	 stddev_cyto_g_stdintensity	 DOUBLE, 
	 avg_cyto_g_entropy	 DOUBLE, 
	 min_cyto_g_entropy	 DOUBLE, 
	 max_cyto_g_entropy	 DOUBLE, 
	 stddev_cyto_g_entropy	 DOUBLE, 
	 avg_cyto_g_energy	 DOUBLE, 
	 min_cyto_g_energy	 DOUBLE, 
	 max_cyto_g_energy	 DOUBLE, 
	 stddev_cyto_g_energy	 DOUBLE, 
	 avg_cyto_g_skewness	 DOUBLE, 
	 min_cyto_g_skewness	 DOUBLE, 
	 max_cyto_g_skewness	 DOUBLE, 
	 stddev_cyto_g_skewness	 DOUBLE, 
	 avg_cyto_g_kurtosis	 DOUBLE, 
	 min_cyto_g_kurtosis	 DOUBLE, 
	 max_cyto_g_kurtosis	 DOUBLE, 
	 stddev_cyto_g_kurtosis	 DOUBLE, 
	 avg_cyto_g_meangradmag	 DOUBLE, 
	 min_cyto_g_meangradmag	 DOUBLE, 
	 max_cyto_g_meangradmag	 DOUBLE, 
	 stddev_cyto_g_meangradmag	 DOUBLE, 
	 avg_cyto_g_stdgradmag	 DOUBLE, 
	 min_cyto_g_stdgradmag	 DOUBLE, 
	 max_cyto_g_stdgradmag	 DOUBLE, 
	 stddev_cyto_g_stdgradmag	 DOUBLE, 
	 avg_cyto_g_entropygradmag	 DOUBLE, 
	 min_cyto_g_entropygradmag	 DOUBLE, 
	 max_cyto_g_entropygradmag	 DOUBLE, 
	 stddev_cyto_g_entropygradmag	 DOUBLE, 
	 avg_cyto_g_energygradmag	 DOUBLE, 
	 min_cyto_g_energygradmag	 DOUBLE, 
	 max_cyto_g_energygradmag	 DOUBLE, 
	 stddev_cyto_g_energygradmag	 DOUBLE, 
	 avg_cyto_g_skewnessgradmag	 DOUBLE, 
	 min_cyto_g_skewnessgradmag	 DOUBLE, 
	 max_cyto_g_skewnessgradmag	 DOUBLE, 
	 stddev_cyto_g_skewnessgradmag	 DOUBLE, 
	 avg_cyto_g_kurtosisgradmag	 DOUBLE, 
	 min_cyto_g_kurtosisgradmag	 DOUBLE, 
	 max_cyto_g_kurtosisgradmag	 DOUBLE, 
	 stddev_cyto_g_kurtosisgradmag	 DOUBLE, 
	 avg_cyto_g_sumcanny	 DOUBLE, 
	 min_cyto_g_sumcanny	 DOUBLE, 
	 max_cyto_g_sumcanny	 DOUBLE, 
	 stddev_cyto_g_sumcanny	 DOUBLE, 
	 avg_cyto_g_meancanny	 DOUBLE, 
	 min_cyto_g_meancanny	 DOUBLE, 
	 max_cyto_g_meancanny	 DOUBLE, 
	 stddev_cyto_g_meancanny	 DOUBLE); 

CREATE TABLE pais.temp_feature_covariance( 
	 pais_uid VARCHAR(64),
	 timestamp TIMESTAMP,
	 f1_1	 DOUBLE, 
	 f2_1	 DOUBLE, 
	 f3_1	 DOUBLE, 
	 f4_1	 DOUBLE, 
	 f5_1	 DOUBLE, 
	 f6_1	 DOUBLE, 
	 f7_1	 DOUBLE, 
	 f8_1	 DOUBLE, 
	 f9_1	 DOUBLE, 
	 f10_1	 DOUBLE, 
	 f11_1	 DOUBLE, 
	 f12_1	 DOUBLE, 
	 f13_1	 DOUBLE, 
	 f14_1	 DOUBLE, 
	 f15_1	 DOUBLE, 
	 f16_1	 DOUBLE, 
	 f17_1	 DOUBLE, 
	 f18_1	 DOUBLE, 
	 f19_1	 DOUBLE, 
	 f20_1	 DOUBLE, 
	 f21_1	 DOUBLE, 
	 f22_1	 DOUBLE, 
	 f23_1	 DOUBLE, 
	 f24_1	 DOUBLE, 
	 f25_1	 DOUBLE, 
	 f26_1	 DOUBLE, 
	 f27_1	 DOUBLE, 
	 f28_1	 DOUBLE, 
	 f29_1	 DOUBLE, 
	 f30_1	 DOUBLE, 
	 f31_1	 DOUBLE, 
	 f32_1	 DOUBLE, 
	 f33_1	 DOUBLE, 
	 f34_1	 DOUBLE, 
	 f35_1	 DOUBLE, 
	 f36_1	 DOUBLE, 
	 f37_1	 DOUBLE, 
	 f38_1	 DOUBLE, 
	 f39_1	 DOUBLE, 
	 f40_1	 DOUBLE, 
	 f41_1	 DOUBLE, 
	 f42_1	 DOUBLE, 
	 f43_1	 DOUBLE, 
	 f44_1	 DOUBLE, 
	 f45_1	 DOUBLE, 
	 f46_1	 DOUBLE, 
	 f47_1	 DOUBLE, 
	 f48_1	 DOUBLE, 
	 f49_1	 DOUBLE, 
	 f50_1	 DOUBLE, 
	 f51_1	 DOUBLE, 
	 f52_1	 DOUBLE, 
	 f53_1	 DOUBLE, 
	 f54_1	 DOUBLE, 
	 f55_1	 DOUBLE, 
	 f56_1	 DOUBLE, 
	 f57_1	 DOUBLE, 
	 f58_1	 DOUBLE, 
	 f59_1	 DOUBLE, 
	 f60_1	 DOUBLE, 
	 f61_1	 DOUBLE, 
	 f62_1	 DOUBLE, 
	 f63_1	 DOUBLE, 
	 f64_1	 DOUBLE, 
	 f65_1	 DOUBLE, 
	 f66_1	 DOUBLE, 
	 f67_1	 DOUBLE, 
	 f68_1	 DOUBLE, 
	 f69_1	 DOUBLE, 
	 f70_1	 DOUBLE, 
	 f71_1	 DOUBLE, 
	 f72_1	 DOUBLE, 
	 f73_1	 DOUBLE, 
	 f74_1	 DOUBLE, 
	 f1_2	 DOUBLE, 
	 f2_2	 DOUBLE, 
	 f3_2	 DOUBLE, 
	 f4_2	 DOUBLE, 
	 f5_2	 DOUBLE, 
	 f6_2	 DOUBLE, 
	 f7_2	 DOUBLE, 
	 f8_2	 DOUBLE, 
	 f9_2	 DOUBLE, 
	 f10_2	 DOUBLE, 
	 f11_2	 DOUBLE, 
	 f12_2	 DOUBLE, 
	 f13_2	 DOUBLE, 
	 f14_2	 DOUBLE, 
	 f15_2	 DOUBLE, 
	 f16_2	 DOUBLE, 
	 f17_2	 DOUBLE, 
	 f18_2	 DOUBLE, 
	 f19_2	 DOUBLE, 
	 f20_2	 DOUBLE, 
	 f21_2	 DOUBLE, 
	 f22_2	 DOUBLE, 
	 f23_2	 DOUBLE, 
	 f24_2	 DOUBLE, 
	 f25_2	 DOUBLE, 
	 f26_2	 DOUBLE, 
	 f27_2	 DOUBLE, 
	 f28_2	 DOUBLE, 
	 f29_2	 DOUBLE, 
	 f30_2	 DOUBLE, 
	 f31_2	 DOUBLE, 
	 f32_2	 DOUBLE, 
	 f33_2	 DOUBLE, 
	 f34_2	 DOUBLE, 
	 f35_2	 DOUBLE, 
	 f36_2	 DOUBLE, 
	 f37_2	 DOUBLE, 
	 f38_2	 DOUBLE, 
	 f39_2	 DOUBLE, 
	 f40_2	 DOUBLE, 
	 f41_2	 DOUBLE, 
	 f42_2	 DOUBLE, 
	 f43_2	 DOUBLE, 
	 f44_2	 DOUBLE, 
	 f45_2	 DOUBLE, 
	 f46_2	 DOUBLE, 
	 f47_2	 DOUBLE, 
	 f48_2	 DOUBLE, 
	 f49_2	 DOUBLE, 
	 f50_2	 DOUBLE, 
	 f51_2	 DOUBLE, 
	 f52_2	 DOUBLE, 
	 f53_2	 DOUBLE, 
	 f54_2	 DOUBLE, 
	 f55_2	 DOUBLE, 
	 f56_2	 DOUBLE, 
	 f57_2	 DOUBLE, 
	 f58_2	 DOUBLE, 
	 f59_2	 DOUBLE, 
	 f60_2	 DOUBLE, 
	 f61_2	 DOUBLE, 
	 f62_2	 DOUBLE, 
	 f63_2	 DOUBLE, 
	 f64_2	 DOUBLE, 
	 f65_2	 DOUBLE, 
	 f66_2	 DOUBLE, 
	 f67_2	 DOUBLE, 
	 f68_2	 DOUBLE, 
	 f69_2	 DOUBLE, 
	 f70_2	 DOUBLE, 
	 f71_2	 DOUBLE, 
	 f72_2	 DOUBLE, 
	 f73_2	 DOUBLE, 
	 f74_2	 DOUBLE, 
	 f1_3	 DOUBLE, 
	 f2_3	 DOUBLE, 
	 f3_3	 DOUBLE, 
	 f4_3	 DOUBLE, 
	 f5_3	 DOUBLE, 
	 f6_3	 DOUBLE, 
	 f7_3	 DOUBLE, 
	 f8_3	 DOUBLE, 
	 f9_3	 DOUBLE, 
	 f10_3	 DOUBLE, 
	 f11_3	 DOUBLE, 
	 f12_3	 DOUBLE, 
	 f13_3	 DOUBLE, 
	 f14_3	 DOUBLE, 
	 f15_3	 DOUBLE, 
	 f16_3	 DOUBLE, 
	 f17_3	 DOUBLE, 
	 f18_3	 DOUBLE, 
	 f19_3	 DOUBLE, 
	 f20_3	 DOUBLE, 
	 f21_3	 DOUBLE, 
	 f22_3	 DOUBLE, 
	 f23_3	 DOUBLE, 
	 f24_3	 DOUBLE, 
	 f25_3	 DOUBLE, 
	 f26_3	 DOUBLE, 
	 f27_3	 DOUBLE, 
	 f28_3	 DOUBLE, 
	 f29_3	 DOUBLE, 
	 f30_3	 DOUBLE, 
	 f31_3	 DOUBLE, 
	 f32_3	 DOUBLE, 
	 f33_3	 DOUBLE, 
	 f34_3	 DOUBLE, 
	 f35_3	 DOUBLE, 
	 f36_3	 DOUBLE, 
	 f37_3	 DOUBLE, 
	 f38_3	 DOUBLE, 
	 f39_3	 DOUBLE, 
	 f40_3	 DOUBLE, 
	 f41_3	 DOUBLE, 
	 f42_3	 DOUBLE, 
	 f43_3	 DOUBLE, 
	 f44_3	 DOUBLE, 
	 f45_3	 DOUBLE, 
	 f46_3	 DOUBLE, 
	 f47_3	 DOUBLE, 
	 f48_3	 DOUBLE, 
	 f49_3	 DOUBLE, 
	 f50_3	 DOUBLE, 
	 f51_3	 DOUBLE, 
	 f52_3	 DOUBLE, 
	 f53_3	 DOUBLE, 
	 f54_3	 DOUBLE, 
	 f55_3	 DOUBLE, 
	 f56_3	 DOUBLE, 
	 f57_3	 DOUBLE, 
	 f58_3	 DOUBLE, 
	 f59_3	 DOUBLE, 
	 f60_3	 DOUBLE, 
	 f61_3	 DOUBLE, 
	 f62_3	 DOUBLE, 
	 f63_3	 DOUBLE, 
	 f64_3	 DOUBLE, 
	 f65_3	 DOUBLE, 
	 f66_3	 DOUBLE, 
	 f67_3	 DOUBLE, 
	 f68_3	 DOUBLE, 
	 f69_3	 DOUBLE, 
	 f70_3	 DOUBLE, 
	 f71_3	 DOUBLE, 
	 f72_3	 DOUBLE, 
	 f73_3	 DOUBLE, 
	 f74_3	 DOUBLE, 
	 f1_4	 DOUBLE, 
	 f2_4	 DOUBLE, 
	 f3_4	 DOUBLE, 
	 f4_4	 DOUBLE, 
	 f5_4	 DOUBLE, 
	 f6_4	 DOUBLE, 
	 f7_4	 DOUBLE, 
	 f8_4	 DOUBLE, 
	 f9_4	 DOUBLE, 
	 f10_4	 DOUBLE, 
	 f11_4	 DOUBLE, 
	 f12_4	 DOUBLE, 
	 f13_4	 DOUBLE, 
	 f14_4	 DOUBLE, 
	 f15_4	 DOUBLE, 
	 f16_4	 DOUBLE, 
	 f17_4	 DOUBLE, 
	 f18_4	 DOUBLE, 
	 f19_4	 DOUBLE, 
	 f20_4	 DOUBLE, 
	 f21_4	 DOUBLE, 
	 f22_4	 DOUBLE, 
	 f23_4	 DOUBLE, 
	 f24_4	 DOUBLE, 
	 f25_4	 DOUBLE, 
	 f26_4	 DOUBLE, 
	 f27_4	 DOUBLE, 
	 f28_4	 DOUBLE, 
	 f29_4	 DOUBLE, 
	 f30_4	 DOUBLE, 
	 f31_4	 DOUBLE, 
	 f32_4	 DOUBLE, 
	 f33_4	 DOUBLE, 
	 f34_4	 DOUBLE, 
	 f35_4	 DOUBLE, 
	 f36_4	 DOUBLE, 
	 f37_4	 DOUBLE, 
	 f38_4	 DOUBLE, 
	 f39_4	 DOUBLE, 
	 f40_4	 DOUBLE, 
	 f41_4	 DOUBLE, 
	 f42_4	 DOUBLE, 
	 f43_4	 DOUBLE, 
	 f44_4	 DOUBLE, 
	 f45_4	 DOUBLE, 
	 f46_4	 DOUBLE, 
	 f47_4	 DOUBLE, 
	 f48_4	 DOUBLE, 
	 f49_4	 DOUBLE, 
	 f50_4	 DOUBLE, 
	 f51_4	 DOUBLE, 
	 f52_4	 DOUBLE, 
	 f53_4	 DOUBLE, 
	 f54_4	 DOUBLE, 
	 f55_4	 DOUBLE, 
	 f56_4	 DOUBLE, 
	 f57_4	 DOUBLE, 
	 f58_4	 DOUBLE, 
	 f59_4	 DOUBLE, 
	 f60_4	 DOUBLE, 
	 f61_4	 DOUBLE, 
	 f62_4	 DOUBLE, 
	 f63_4	 DOUBLE, 
	 f64_4	 DOUBLE, 
	 f65_4	 DOUBLE, 
	 f66_4	 DOUBLE, 
	 f67_4	 DOUBLE, 
	 f68_4	 DOUBLE, 
	 f69_4	 DOUBLE, 
	 f70_4	 DOUBLE, 
	 f71_4	 DOUBLE, 
	 f72_4	 DOUBLE, 
	 f73_4	 DOUBLE, 
	 f74_4	 DOUBLE, 
	 f1_5	 DOUBLE, 
	 f2_5	 DOUBLE, 
	 f3_5	 DOUBLE, 
	 f4_5	 DOUBLE, 
	 f5_5	 DOUBLE, 
	 f6_5	 DOUBLE, 
	 f7_5	 DOUBLE, 
	 f8_5	 DOUBLE, 
	 f9_5	 DOUBLE, 
	 f10_5	 DOUBLE, 
	 f11_5	 DOUBLE, 
	 f12_5	 DOUBLE, 
	 f13_5	 DOUBLE, 
	 f14_5	 DOUBLE, 
	 f15_5	 DOUBLE, 
	 f16_5	 DOUBLE, 
	 f17_5	 DOUBLE, 
	 f18_5	 DOUBLE, 
	 f19_5	 DOUBLE, 
	 f20_5	 DOUBLE, 
	 f21_5	 DOUBLE, 
	 f22_5	 DOUBLE, 
	 f23_5	 DOUBLE, 
	 f24_5	 DOUBLE, 
	 f25_5	 DOUBLE, 
	 f26_5	 DOUBLE, 
	 f27_5	 DOUBLE, 
	 f28_5	 DOUBLE, 
	 f29_5	 DOUBLE, 
	 f30_5	 DOUBLE, 
	 f31_5	 DOUBLE, 
	 f32_5	 DOUBLE, 
	 f33_5	 DOUBLE, 
	 f34_5	 DOUBLE, 
	 f35_5	 DOUBLE, 
	 f36_5	 DOUBLE, 
	 f37_5	 DOUBLE, 
	 f38_5	 DOUBLE, 
	 f39_5	 DOUBLE, 
	 f40_5	 DOUBLE, 
	 f41_5	 DOUBLE, 
	 f42_5	 DOUBLE, 
	 f43_5	 DOUBLE, 
	 f44_5	 DOUBLE, 
	 f45_5	 DOUBLE, 
	 f46_5	 DOUBLE, 
	 f47_5	 DOUBLE, 
	 f48_5	 DOUBLE, 
	 f49_5	 DOUBLE, 
	 f50_5	 DOUBLE, 
	 f51_5	 DOUBLE, 
	 f52_5	 DOUBLE, 
	 f53_5	 DOUBLE, 
	 f54_5	 DOUBLE, 
	 f55_5	 DOUBLE, 
	 f56_5	 DOUBLE, 
	 f57_5	 DOUBLE, 
	 f58_5	 DOUBLE, 
	 f59_5	 DOUBLE, 
	 f60_5	 DOUBLE, 
	 f61_5	 DOUBLE, 
	 f62_5	 DOUBLE, 
	 f63_5	 DOUBLE, 
	 f64_5	 DOUBLE, 
	 f65_5	 DOUBLE, 
	 f66_5	 DOUBLE, 
	 f67_5	 DOUBLE, 
	 f68_5	 DOUBLE, 
	 f69_5	 DOUBLE, 
	 f70_5	 DOUBLE, 
	 f71_5	 DOUBLE, 
	 f72_5	 DOUBLE, 
	 f73_5	 DOUBLE, 
	 f74_5	 DOUBLE, 
	 f1_6	 DOUBLE, 
	 f2_6	 DOUBLE, 
	 f3_6	 DOUBLE, 
	 f4_6	 DOUBLE, 
	 f5_6	 DOUBLE, 
	 f6_6	 DOUBLE, 
	 f7_6	 DOUBLE, 
	 f8_6	 DOUBLE, 
	 f9_6	 DOUBLE, 
	 f10_6	 DOUBLE, 
	 f11_6	 DOUBLE, 
	 f12_6	 DOUBLE, 
	 f13_6	 DOUBLE, 
	 f14_6	 DOUBLE, 
	 f15_6	 DOUBLE, 
	 f16_6	 DOUBLE, 
	 f17_6	 DOUBLE, 
	 f18_6	 DOUBLE, 
	 f19_6	 DOUBLE, 
	 f20_6	 DOUBLE, 
	 f21_6	 DOUBLE, 
	 f22_6	 DOUBLE, 
	 f23_6	 DOUBLE, 
	 f24_6	 DOUBLE, 
	 f25_6	 DOUBLE, 
	 f26_6	 DOUBLE, 
	 f27_6	 DOUBLE, 
	 f28_6	 DOUBLE, 
	 f29_6	 DOUBLE, 
	 f30_6	 DOUBLE, 
	 f31_6	 DOUBLE, 
	 f32_6	 DOUBLE, 
	 f33_6	 DOUBLE, 
	 f34_6	 DOUBLE, 
	 f35_6	 DOUBLE, 
	 f36_6	 DOUBLE, 
	 f37_6	 DOUBLE, 
	 f38_6	 DOUBLE, 
	 f39_6	 DOUBLE, 
	 f40_6	 DOUBLE, 
	 f41_6	 DOUBLE, 
	 f42_6	 DOUBLE, 
	 f43_6	 DOUBLE, 
	 f44_6	 DOUBLE, 
	 f45_6	 DOUBLE, 
	 f46_6	 DOUBLE, 
	 f47_6	 DOUBLE, 
	 f48_6	 DOUBLE, 
	 f49_6	 DOUBLE, 
	 f50_6	 DOUBLE, 
	 f51_6	 DOUBLE, 
	 f52_6	 DOUBLE, 
	 f53_6	 DOUBLE, 
	 f54_6	 DOUBLE, 
	 f55_6	 DOUBLE, 
	 f56_6	 DOUBLE, 
	 f57_6	 DOUBLE, 
	 f58_6	 DOUBLE, 
	 f59_6	 DOUBLE, 
	 f60_6	 DOUBLE, 
	 f61_6	 DOUBLE, 
	 f62_6	 DOUBLE, 
	 f63_6	 DOUBLE, 
	 f64_6	 DOUBLE, 
	 f65_6	 DOUBLE, 
	 f66_6	 DOUBLE, 
	 f67_6	 DOUBLE, 
	 f68_6	 DOUBLE, 
	 f69_6	 DOUBLE, 
	 f70_6	 DOUBLE, 
	 f71_6	 DOUBLE, 
	 f72_6	 DOUBLE, 
	 f73_6	 DOUBLE, 
	 f74_6	 DOUBLE, 
	 f1_7	 DOUBLE, 
	 f2_7	 DOUBLE, 
	 f3_7	 DOUBLE, 
	 f4_7	 DOUBLE, 
	 f5_7	 DOUBLE, 
	 f6_7	 DOUBLE, 
	 f7_7	 DOUBLE, 
	 f8_7	 DOUBLE, 
	 f9_7	 DOUBLE, 
	 f10_7	 DOUBLE, 
	 f11_7	 DOUBLE, 
	 f12_7	 DOUBLE, 
	 f13_7	 DOUBLE, 
	 f14_7	 DOUBLE, 
	 f15_7	 DOUBLE, 
	 f16_7	 DOUBLE, 
	 f17_7	 DOUBLE, 
	 f18_7	 DOUBLE, 
	 f19_7	 DOUBLE, 
	 f20_7	 DOUBLE, 
	 f21_7	 DOUBLE, 
	 f22_7	 DOUBLE, 
	 f23_7	 DOUBLE, 
	 f24_7	 DOUBLE, 
	 f25_7	 DOUBLE, 
	 f26_7	 DOUBLE, 
	 f27_7	 DOUBLE, 
	 f28_7	 DOUBLE, 
	 f29_7	 DOUBLE, 
	 f30_7	 DOUBLE, 
	 f31_7	 DOUBLE, 
	 f32_7	 DOUBLE, 
	 f33_7	 DOUBLE, 
	 f34_7	 DOUBLE, 
	 f35_7	 DOUBLE, 
	 f36_7	 DOUBLE, 
	 f37_7	 DOUBLE, 
	 f38_7	 DOUBLE, 
	 f39_7	 DOUBLE, 
	 f40_7	 DOUBLE, 
	 f41_7	 DOUBLE, 
	 f42_7	 DOUBLE, 
	 f43_7	 DOUBLE, 
	 f44_7	 DOUBLE, 
	 f45_7	 DOUBLE, 
	 f46_7	 DOUBLE, 
	 f47_7	 DOUBLE, 
	 f48_7	 DOUBLE, 
	 f49_7	 DOUBLE, 
	 f50_7	 DOUBLE, 
	 f51_7	 DOUBLE, 
	 f52_7	 DOUBLE, 
	 f53_7	 DOUBLE, 
	 f54_7	 DOUBLE, 
	 f55_7	 DOUBLE, 
	 f56_7	 DOUBLE, 
	 f57_7	 DOUBLE, 
	 f58_7	 DOUBLE, 
	 f59_7	 DOUBLE, 
	 f60_7	 DOUBLE, 
	 f61_7	 DOUBLE, 
	 f62_7	 DOUBLE, 
	 f63_7	 DOUBLE, 
	 f64_7	 DOUBLE, 
	 f65_7	 DOUBLE, 
	 f66_7	 DOUBLE, 
	 f67_7	 DOUBLE, 
	 f68_7	 DOUBLE, 
	 f69_7	 DOUBLE, 
	 f70_7	 DOUBLE, 
	 f71_7	 DOUBLE, 
	 f72_7	 DOUBLE, 
	 f73_7	 DOUBLE, 
	 f74_7	 DOUBLE, 
	 f1_8	 DOUBLE, 
	 f2_8	 DOUBLE, 
	 f3_8	 DOUBLE, 
	 f4_8	 DOUBLE, 
	 f5_8	 DOUBLE, 
	 f6_8	 DOUBLE, 
	 f7_8	 DOUBLE, 
	 f8_8	 DOUBLE, 
	 f9_8	 DOUBLE, 
	 f10_8	 DOUBLE, 
	 f11_8	 DOUBLE, 
	 f12_8	 DOUBLE, 
	 f13_8	 DOUBLE, 
	 f14_8	 DOUBLE, 
	 f15_8	 DOUBLE, 
	 f16_8	 DOUBLE, 
	 f17_8	 DOUBLE, 
	 f18_8	 DOUBLE, 
	 f19_8	 DOUBLE, 
	 f20_8	 DOUBLE, 
	 f21_8	 DOUBLE, 
	 f22_8	 DOUBLE, 
	 f23_8	 DOUBLE, 
	 f24_8	 DOUBLE, 
	 f25_8	 DOUBLE, 
	 f26_8	 DOUBLE, 
	 f27_8	 DOUBLE, 
	 f28_8	 DOUBLE, 
	 f29_8	 DOUBLE, 
	 f30_8	 DOUBLE, 
	 f31_8	 DOUBLE, 
	 f32_8	 DOUBLE, 
	 f33_8	 DOUBLE, 
	 f34_8	 DOUBLE, 
	 f35_8	 DOUBLE, 
	 f36_8	 DOUBLE, 
	 f37_8	 DOUBLE, 
	 f38_8	 DOUBLE, 
	 f39_8	 DOUBLE, 
	 f40_8	 DOUBLE, 
	 f41_8	 DOUBLE, 
	 f42_8	 DOUBLE, 
	 f43_8	 DOUBLE, 
	 f44_8	 DOUBLE, 
	 f45_8	 DOUBLE, 
	 f46_8	 DOUBLE, 
	 f47_8	 DOUBLE, 
	 f48_8	 DOUBLE, 
	 f49_8	 DOUBLE, 
	 f50_8	 DOUBLE, 
	 f51_8	 DOUBLE, 
	 f52_8	 DOUBLE, 
	 f53_8	 DOUBLE, 
	 f54_8	 DOUBLE, 
	 f55_8	 DOUBLE, 
	 f56_8	 DOUBLE, 
	 f57_8	 DOUBLE, 
	 f58_8	 DOUBLE, 
	 f59_8	 DOUBLE, 
	 f60_8	 DOUBLE, 
	 f61_8	 DOUBLE, 
	 f62_8	 DOUBLE, 
	 f63_8	 DOUBLE, 
	 f64_8	 DOUBLE, 
	 f65_8	 DOUBLE, 
	 f66_8	 DOUBLE, 
	 f67_8	 DOUBLE, 
	 f68_8	 DOUBLE, 
	 f69_8	 DOUBLE, 
	 f70_8	 DOUBLE, 
	 f71_8	 DOUBLE, 
	 f72_8	 DOUBLE, 
	 f73_8	 DOUBLE, 
	 f74_8	 DOUBLE, 
	 f1_9	 DOUBLE, 
	 f2_9	 DOUBLE, 
	 f3_9	 DOUBLE, 
	 f4_9	 DOUBLE, 
	 f5_9	 DOUBLE, 
	 f6_9	 DOUBLE, 
	 f7_9	 DOUBLE, 
	 f8_9	 DOUBLE, 
	 f9_9	 DOUBLE, 
	 f10_9	 DOUBLE, 
	 f11_9	 DOUBLE, 
	 f12_9	 DOUBLE, 
	 f13_9	 DOUBLE, 
	 f14_9	 DOUBLE, 
	 f15_9	 DOUBLE, 
	 f16_9	 DOUBLE, 
	 f17_9	 DOUBLE, 
	 f18_9	 DOUBLE, 
	 f19_9	 DOUBLE, 
	 f20_9	 DOUBLE, 
	 f21_9	 DOUBLE, 
	 f22_9	 DOUBLE, 
	 f23_9	 DOUBLE, 
	 f24_9	 DOUBLE, 
	 f25_9	 DOUBLE, 
	 f26_9	 DOUBLE, 
	 f27_9	 DOUBLE, 
	 f28_9	 DOUBLE, 
	 f29_9	 DOUBLE, 
	 f30_9	 DOUBLE, 
	 f31_9	 DOUBLE, 
	 f32_9	 DOUBLE, 
	 f33_9	 DOUBLE, 
	 f34_9	 DOUBLE, 
	 f35_9	 DOUBLE, 
	 f36_9	 DOUBLE, 
	 f37_9	 DOUBLE, 
	 f38_9	 DOUBLE, 
	 f39_9	 DOUBLE, 
	 f40_9	 DOUBLE, 
	 f41_9	 DOUBLE, 
	 f42_9	 DOUBLE, 
	 f43_9	 DOUBLE, 
	 f44_9	 DOUBLE, 
	 f45_9	 DOUBLE, 
	 f46_9	 DOUBLE, 
	 f47_9	 DOUBLE, 
	 f48_9	 DOUBLE, 
	 f49_9	 DOUBLE, 
	 f50_9	 DOUBLE, 
	 f51_9	 DOUBLE, 
	 f52_9	 DOUBLE, 
	 f53_9	 DOUBLE, 
	 f54_9	 DOUBLE, 
	 f55_9	 DOUBLE, 
	 f56_9	 DOUBLE, 
	 f57_9	 DOUBLE, 
	 f58_9	 DOUBLE, 
	 f59_9	 DOUBLE, 
	 f60_9	 DOUBLE, 
	 f61_9	 DOUBLE, 
	 f62_9	 DOUBLE, 
	 f63_9	 DOUBLE, 
	 f64_9	 DOUBLE, 
	 f65_9	 DOUBLE, 
	 f66_9	 DOUBLE, 
	 f67_9	 DOUBLE, 
	 f68_9	 DOUBLE, 
	 f69_9	 DOUBLE, 
	 f70_9	 DOUBLE, 
	 f71_9	 DOUBLE, 
	 f72_9	 DOUBLE, 
	 f73_9	 DOUBLE, 
	 f74_9	 DOUBLE, 
	 f1_10	 DOUBLE, 
	 f2_10	 DOUBLE, 
	 f3_10	 DOUBLE, 
	 f4_10	 DOUBLE, 
	 f5_10	 DOUBLE, 
	 f6_10	 DOUBLE, 
	 f7_10	 DOUBLE, 
	 f8_10	 DOUBLE, 
	 f9_10	 DOUBLE, 
	 f10_10	 DOUBLE, 
	 f11_10	 DOUBLE, 
	 f12_10	 DOUBLE, 
	 f13_10	 DOUBLE, 
	 f14_10	 DOUBLE, 
	 f15_10	 DOUBLE, 
	 f16_10	 DOUBLE, 
	 f17_10	 DOUBLE, 
	 f18_10	 DOUBLE, 
	 f19_10	 DOUBLE, 
	 f20_10	 DOUBLE, 
	 f21_10	 DOUBLE, 
	 f22_10	 DOUBLE, 
	 f23_10	 DOUBLE, 
	 f24_10	 DOUBLE, 
	 f25_10	 DOUBLE, 
	 f26_10	 DOUBLE, 
	 f27_10	 DOUBLE, 
	 f28_10	 DOUBLE, 
	 f29_10	 DOUBLE, 
	 f30_10	 DOUBLE, 
	 f31_10	 DOUBLE, 
	 f32_10	 DOUBLE, 
	 f33_10	 DOUBLE, 
	 f34_10	 DOUBLE, 
	 f35_10	 DOUBLE, 
	 f36_10	 DOUBLE, 
	 f37_10	 DOUBLE, 
	 f38_10	 DOUBLE, 
	 f39_10	 DOUBLE, 
	 f40_10	 DOUBLE, 
	 f41_10	 DOUBLE, 
	 f42_10	 DOUBLE, 
	 f43_10	 DOUBLE, 
	 f44_10	 DOUBLE, 
	 f45_10	 DOUBLE, 
	 f46_10	 DOUBLE, 
	 f47_10	 DOUBLE, 
	 f48_10	 DOUBLE, 
	 f49_10	 DOUBLE, 
	 f50_10	 DOUBLE, 
	 f51_10	 DOUBLE, 
	 f52_10	 DOUBLE, 
	 f53_10	 DOUBLE, 
	 f54_10	 DOUBLE, 
	 f55_10	 DOUBLE, 
	 f56_10	 DOUBLE, 
	 f57_10	 DOUBLE, 
	 f58_10	 DOUBLE, 
	 f59_10	 DOUBLE, 
	 f60_10	 DOUBLE, 
	 f61_10	 DOUBLE, 
	 f62_10	 DOUBLE, 
	 f63_10	 DOUBLE, 
	 f64_10	 DOUBLE, 
	 f65_10	 DOUBLE, 
	 f66_10	 DOUBLE, 
	 f67_10	 DOUBLE, 
	 f68_10	 DOUBLE, 
	 f69_10	 DOUBLE, 
	 f70_10	 DOUBLE, 
	 f71_10	 DOUBLE, 
	 f72_10	 DOUBLE, 
	 f73_10	 DOUBLE, 
	 f74_10	 DOUBLE, 
	 f1_11	 DOUBLE, 
	 f2_11	 DOUBLE, 
	 f3_11	 DOUBLE, 
	 f4_11	 DOUBLE, 
	 f5_11	 DOUBLE, 
	 f6_11	 DOUBLE, 
	 f7_11	 DOUBLE, 
	 f8_11	 DOUBLE, 
	 f9_11	 DOUBLE, 
	 f10_11	 DOUBLE, 
	 f11_11	 DOUBLE, 
	 f12_11	 DOUBLE, 
	 f13_11	 DOUBLE, 
	 f14_11	 DOUBLE, 
	 f15_11	 DOUBLE, 
	 f16_11	 DOUBLE, 
	 f17_11	 DOUBLE, 
	 f18_11	 DOUBLE, 
	 f19_11	 DOUBLE, 
	 f20_11	 DOUBLE, 
	 f21_11	 DOUBLE, 
	 f22_11	 DOUBLE, 
	 f23_11	 DOUBLE, 
	 f24_11	 DOUBLE, 
	 f25_11	 DOUBLE, 
	 f26_11	 DOUBLE, 
	 f27_11	 DOUBLE, 
	 f28_11	 DOUBLE, 
	 f29_11	 DOUBLE, 
	 f30_11	 DOUBLE, 
	 f31_11	 DOUBLE, 
	 f32_11	 DOUBLE, 
	 f33_11	 DOUBLE, 
	 f34_11	 DOUBLE, 
	 f35_11	 DOUBLE, 
	 f36_11	 DOUBLE, 
	 f37_11	 DOUBLE, 
	 f38_11	 DOUBLE, 
	 f39_11	 DOUBLE, 
	 f40_11	 DOUBLE, 
	 f41_11	 DOUBLE, 
	 f42_11	 DOUBLE, 
	 f43_11	 DOUBLE, 
	 f44_11	 DOUBLE, 
	 f45_11	 DOUBLE, 
	 f46_11	 DOUBLE, 
	 f47_11	 DOUBLE, 
	 f48_11	 DOUBLE, 
	 f49_11	 DOUBLE, 
	 f50_11	 DOUBLE, 
	 f51_11	 DOUBLE, 
	 f52_11	 DOUBLE, 
	 f53_11	 DOUBLE, 
	 f54_11	 DOUBLE, 
	 f55_11	 DOUBLE, 
	 f56_11	 DOUBLE, 
	 f57_11	 DOUBLE, 
	 f58_11	 DOUBLE, 
	 f59_11	 DOUBLE, 
	 f60_11	 DOUBLE, 
	 f61_11	 DOUBLE, 
	 f62_11	 DOUBLE, 
	 f63_11	 DOUBLE, 
	 f64_11	 DOUBLE, 
	 f65_11	 DOUBLE, 
	 f66_11	 DOUBLE, 
	 f67_11	 DOUBLE, 
	 f68_11	 DOUBLE, 
	 f69_11	 DOUBLE, 
	 f70_11	 DOUBLE, 
	 f71_11	 DOUBLE, 
	 f72_11	 DOUBLE, 
	 f73_11	 DOUBLE, 
	 f74_11	 DOUBLE, 
	 f1_12	 DOUBLE, 
	 f2_12	 DOUBLE, 
	 f3_12	 DOUBLE, 
	 f4_12	 DOUBLE, 
	 f5_12	 DOUBLE, 
	 f6_12	 DOUBLE, 
	 f7_12	 DOUBLE, 
	 f8_12	 DOUBLE, 
	 f9_12	 DOUBLE, 
	 f10_12	 DOUBLE, 
	 f11_12	 DOUBLE, 
	 f12_12	 DOUBLE, 
	 f13_12	 DOUBLE, 
	 f14_12	 DOUBLE, 
	 f15_12	 DOUBLE, 
	 f16_12	 DOUBLE, 
	 f17_12	 DOUBLE, 
	 f18_12	 DOUBLE, 
	 f19_12	 DOUBLE, 
	 f20_12	 DOUBLE, 
	 f21_12	 DOUBLE, 
	 f22_12	 DOUBLE, 
	 f23_12	 DOUBLE, 
	 f24_12	 DOUBLE, 
	 f25_12	 DOUBLE, 
	 f26_12	 DOUBLE, 
	 f27_12	 DOUBLE, 
	 f28_12	 DOUBLE, 
	 f29_12	 DOUBLE, 
	 f30_12	 DOUBLE, 
	 f31_12	 DOUBLE, 
	 f32_12	 DOUBLE, 
	 f33_12	 DOUBLE, 
	 f34_12	 DOUBLE, 
	 f35_12	 DOUBLE, 
	 f36_12	 DOUBLE, 
	 f37_12	 DOUBLE, 
	 f38_12	 DOUBLE, 
	 f39_12	 DOUBLE, 
	 f40_12	 DOUBLE, 
	 f41_12	 DOUBLE, 
	 f42_12	 DOUBLE, 
	 f43_12	 DOUBLE, 
	 f44_12	 DOUBLE, 
	 f45_12	 DOUBLE, 
	 f46_12	 DOUBLE, 
	 f47_12	 DOUBLE, 
	 f48_12	 DOUBLE, 
	 f49_12	 DOUBLE, 
	 f50_12	 DOUBLE, 
	 f51_12	 DOUBLE, 
	 f52_12	 DOUBLE, 
	 f53_12	 DOUBLE, 
	 f54_12	 DOUBLE, 
	 f55_12	 DOUBLE, 
	 f56_12	 DOUBLE, 
	 f57_12	 DOUBLE, 
	 f58_12	 DOUBLE, 
	 f59_12	 DOUBLE, 
	 f60_12	 DOUBLE, 
	 f61_12	 DOUBLE, 
	 f62_12	 DOUBLE, 
	 f63_12	 DOUBLE, 
	 f64_12	 DOUBLE, 
	 f65_12	 DOUBLE, 
	 f66_12	 DOUBLE, 
	 f67_12	 DOUBLE, 
	 f68_12	 DOUBLE, 
	 f69_12	 DOUBLE, 
	 f70_12	 DOUBLE, 
	 f71_12	 DOUBLE, 
	 f72_12	 DOUBLE, 
	 f73_12	 DOUBLE, 
	 f74_12	 DOUBLE, 
	 f1_13	 DOUBLE, 
	 f2_13	 DOUBLE, 
	 f3_13	 DOUBLE, 
	 f4_13	 DOUBLE, 
	 f5_13	 DOUBLE, 
	 f6_13	 DOUBLE, 
	 f7_13	 DOUBLE, 
	 f8_13	 DOUBLE, 
	 f9_13	 DOUBLE, 
	 f10_13	 DOUBLE, 
	 f11_13	 DOUBLE, 
	 f12_13	 DOUBLE, 
	 f13_13	 DOUBLE, 
	 f14_13	 DOUBLE, 
	 f15_13	 DOUBLE, 
	 f16_13	 DOUBLE, 
	 f17_13	 DOUBLE, 
	 f18_13	 DOUBLE, 
	 f19_13	 DOUBLE, 
	 f20_13	 DOUBLE, 
	 f21_13	 DOUBLE, 
	 f22_13	 DOUBLE, 
	 f23_13	 DOUBLE, 
	 f24_13	 DOUBLE, 
	 f25_13	 DOUBLE, 
	 f26_13	 DOUBLE, 
	 f27_13	 DOUBLE, 
	 f28_13	 DOUBLE, 
	 f29_13	 DOUBLE, 
	 f30_13	 DOUBLE, 
	 f31_13	 DOUBLE, 
	 f32_13	 DOUBLE, 
	 f33_13	 DOUBLE, 
	 f34_13	 DOUBLE, 
	 f35_13	 DOUBLE, 
	 f36_13	 DOUBLE, 
	 f37_13	 DOUBLE, 
	 f38_13	 DOUBLE, 
	 f39_13	 DOUBLE, 
	 f40_13	 DOUBLE, 
	 f41_13	 DOUBLE, 
	 f42_13	 DOUBLE, 
	 f43_13	 DOUBLE, 
	 f44_13	 DOUBLE, 
	 f45_13	 DOUBLE, 
	 f46_13	 DOUBLE, 
	 f47_13	 DOUBLE, 
	 f48_13	 DOUBLE, 
	 f49_13	 DOUBLE, 
	 f50_13	 DOUBLE, 
	 f51_13	 DOUBLE, 
	 f52_13	 DOUBLE, 
	 f53_13	 DOUBLE, 
	 f54_13	 DOUBLE, 
	 f55_13	 DOUBLE, 
	 f56_13	 DOUBLE, 
	 f57_13	 DOUBLE, 
	 f58_13	 DOUBLE, 
	 f59_13	 DOUBLE, 
	 f60_13	 DOUBLE, 
	 f61_13	 DOUBLE, 
	 f62_13	 DOUBLE, 
	 f63_13	 DOUBLE, 
	 f64_13	 DOUBLE, 
	 f65_13	 DOUBLE, 
	 f66_13	 DOUBLE, 
	 f67_13	 DOUBLE, 
	 f68_13	 DOUBLE, 
	 f69_13	 DOUBLE, 
	 f70_13	 DOUBLE, 
	 f71_13	 DOUBLE, 
	 f72_13	 DOUBLE, 
	 f73_13	 DOUBLE, 
	 f74_13	 DOUBLE);



echo 'cal_mid';
CREATE INDEX PAIS.CAL_MID ON PAIS.CALCULATION_FLAT(PAIS_UID, MARKUP_ID);

echo 'mkp_plgn_tile';
--CREATE INDEX PAIS.mkp_plgn_tile  ON PAIS.MARKUP_POLYGON(pais_uid,tilename);
CREATE INDEX PAIS.mkp_plgn_tile ON PAIS.MARKUP_POLYGON(POLYGON) 
	extend using db2gse.spatial_index(100,0,0);
COMMIT WORK;

--CREATE INDEX PAIS.mkp_plgn_hmn_tile  ON PAIS.MARKUP_POLYGON_HUMAN(pais_uid,tilename);

echo 'obs_nom';
--CREATE INDEX PAIS.obs_nom_name  ON  pais.observation_quantification_nominal(OBSERVATION_NAME);
--CREATE INDEX PAIS.obs_nom_quant_value ON  pais.observation_quantification_nominal(quantification_value);

CREATE INDEX PAIS.obs_nom_name  ON  pais.observation_quantification_nominal(OBSERVATION_NAME, quantification_value);
CREATE INDEX PAIS.obs_nom_mid  ON  pais.observation_quantification_nominal(PAIS_UID, MARKUP_ID);

echo 'obs_ord';
--CREATE INDEX PAIS.obs_ord_name  ON  pais.observation_quantification_ordinal(OBSERVATION_NAME);
--CREATE INDEX PAIS.obs_ord_quant_value ON  pais.observation_quantification_ordinal(quantification_value);

CREATE INDEX PAIS.obs_ord_name  ON  pais.observation_quantification_ordinal(OBSERVATION_NAME, quantification_value);
CREATE INDEX PAIS.obs_ord_mid  ON  pais.observation_quantification_ordinal(PAIS_UID, MARKUP_ID);

CREATE INDEX pais.feature_agg_idx on pais.feature_aggregate(pais_uid, feature);
CREATE INDEX pais.feature_histo_idx on pais.feature_histogram(pais_uid, feature);
CREATE INDEX pais.feature_mean_vec_idx on pais.mean_feature_vector(pais_uid);

RUNSTATS ON TABLE pais.markup_polygon with distribution AND sampled detailed INDEXES ALL;
RUNSTATS ON TABLE PAIS.CALCULATION_FLAT AND INDEXES ALL;
RUNSTATS ON TABLE pais.observation_quantification_nominal AND INDEXES ALL;
RUNSTATS ON TABLE pais.observation_quantification_ordinal AND INDEXES ALL;
RUNSTATS ON TABLE pais.region AND INDEXES ALL;
RUNSTATS ON TABLE pais.collection AND INDEXES ALL;
RUNSTATS ON TABLE pais.patient AND INDEXES ALL;

RUNSTATS ON TABLE pais.provenance AND INDEXES ALL;
RUNSTATS ON TABLE pais.algorithm AND INDEXES ALL;  
RUNSTATS ON TABLE pais.parameter AND INDEXES ALL; 

COMMIT WORK;

 


 




