DROP TABLE PAIS.STAGINGDOC;
DROP TABLE PAIS.LOADING_LOG;
DROP TABLE PAIS.METADOC;
DROP TABLE PAIS.PAIS;
DROP TABLE PAIS.PROJECT;
DROP TABLE PAIS.GROUP;
DROP TABLE PAIS.USER;
DROP TABLE PAIS.COLLECTION;
DROP TABLE PAIS.WHOLESLIDEIMAGEREFERENCE;
DROP TABLE PAIS.REGION;
DROP TABLE PAIS.SPECIMEN;
DROP TABLE PAIS.ANATOMICENTITY;
DROP TABLE PAIS.PATIENT;

DROP TABLE PAIS.OBSERVATION_QUANTIFICATION_ORDINAL;
DROP TABLE PAIS.OBSERVATION_QUANTIFICATION_NOMINAL;
DROP TABLE PAIS.ANNOTATION_MARKUP;

DROP TABLE PAIS.PROVENANCE;
DROP TABLE PAIS.ALGORITHM;
DROP TABLE PAIS.PARAMETER;
DROP TABLE PAIS.INPUTFILEREFERENCE;

DROP TABLE PAIS.CALCULATION_FLAT;
DROP TABLE PAIS.CALCULATION_DICTIONARY;
DROP TABLE PAIS.OBSERVATION_DICTIONARY;

DROP TABLE PAIS.DLMSTATUS;
DROP TABLE PAIS.TEMPLATE;
DROP TABLE PAIS.FEATURES;
DROP TABLE PAIS.TEMPLATEFEATURESRL;



CREATE TABLE PAIS.STAGINGDOC(
	UID	 		VARCHAR(64),  
	TILENAME 		VARCHAR(64), 
	BLOB 			BLOB (1024M) NOT  LOGGED  NOT  COMPACT, 
	STATUS 			VARCHAR(24) WITH DEFAULT 'INCOMPLETE',
	INSERT_TIME		TIMESTAMP,
	COMPLETE_TIME		TIMESTAMP,
	COMPLETE_COUNT		INTEGER,
	LOADING_TIME		DECIMAL(6,2),
	FILE_NAME		VARCHAR(256),
	SEQUENCE_NUMBER		INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE), 
	LOADINGCONFIG   VARCHAR(60),
        PRIMARY KEY(SEQUENCE_NUMBER)
	) in spatialtbs32k;

CREATE TABLE PAIS.LOADING_LOG(
    SEQUENCE_NUMBER             INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    FAILURE_TIME 	        TIMESTAMP,
    FILE_NAME	                VARCHAR(256),
    FAILURE_MESSAGE	        VARCHAR(3000) 
)in spatialtbs32k;

--Added:
  CREATE TABLE PAIS.METADOC(
    UID                         VARCHAR(640) NOT NULL,
    XMLDOC                      XML,
    INSERTTIME                  TIMESTAMP
  );


  CREATE TABLE PAIS.PAIS(
    PAIS_ID			DECIMAL(30,0) NOT NULL,
    PAIS_UID			VARCHAR(64)   NOT NULL,
    NAME			VARCHAR(64),
    DATETIME			VARCHAR(64),
    PAISVERSION			VARCHAR(64),
    CODEVALUE			VARCHAR(64),  
    CODEMEANING			VARCHAR(64),
    CODINGSCHEMEDESIGNATOR	VARCHAR(64),
    CODINGSCHEMEVERSION		VARCHAR(64),  
    COMMENT			VARCHAR(128)
  );



CREATE TABLE PAIS.PROJECT(  
  PROJECT_ID 			DECIMAL(30,0) NOT NULL,
  PROJECT_UID			VARCHAR(64),
  NAME	 			VARCHAR(64),
  URI				VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL
);  


CREATE TABLE PAIS.GROUP(  
  GROUP_ID 			DECIMAL(30,0) NOT NULL,
  GROUP_UID			VARCHAR(64),
  NAME	 			VARCHAR(64),
  URI				VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL
);  


CREATE TABLE PAIS.USER(
  USER_ID			DECIMAL(30,0) NOT NULL,
  LOGINNAME			VARCHAR(64),
  NAME				VARCHAR(64),
  NUMBERWITHINROLEOFCLINICALTRIAL INTEGER,
  ROLEINTRIAL			VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL
);  



CREATE TABLE PAIS.COLLECTION(  
  COLLECTION_ID 		DECIMAL(30,0) NOT NULL,
  COLLECTION_UID		VARCHAR(64) NOT NULL,
  NAME	 			VARCHAR(64),
  ROLE				VARCHAR(64),
  METHODNAME			VARCHAR(64) NOT NULL,
  SEQUENCENUMBER		INTEGER NOT NULL,
  STUDYDATETIME	        	VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL 
);  
  
 
 

 CREATE TABLE PAIS.WHOLESLIDEIMAGEREFERENCE(
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,
  IMAGEREFERENCE_UID		VARCHAR(64),
  FILEREFERENCE			VARCHAR(64),
  URI				VARCHAR(64),
  RESOLUTION			DOUBLE,
  ZAXISRESOLUTION		DOUBLE,
  ZAXISCOORDINTE		DOUBLE,
  PAIS_UID			VARCHAR(64)   NOT NULL 
);    
  


 CREATE TABLE PAIS.REGION(
  REGION_ID			DECIMAL(30,0) NOT NULL,
  NAME				VARCHAR(64) NOT NULL,
  X				DOUBLE,
  Y				DOUBLE,
  HEIGHT			DOUBLE,
  WIDTH				DOUBLE,
  ZOOMRESOLUTION		DOUBLE,
  COORDINATERESOLUTION		DOUBLE,
  COORDINATEREFERENCE		VARCHAR(64),
  POLYGON  			DB2GSE.ST_POLYGON INLINE LENGTH 512,  
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,
  PAIS_UID			VARCHAR(64)   NOT NULL
) in spatialtbs32k;   
  

 CREATE TABLE PAIS.SPECIMEN(
  SPECIMEN_ID			DECIMAL(30,0) NOT NULL,
  SPECIMEN_UID			VARCHAR(64),
  TYPE				VARCHAR(64),
  STAIN				VARCHAR(64),
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,    
  PAIS_UID			VARCHAR(64)   NOT NULL 
);    



 CREATE TABLE PAIS.ANATOMICENTITY(
  ANATOMICENTITY_ID		DECIMAL(30,0) NOT NULL,
  CODEVALUE			VARCHAR(64),  
  CODEMEANING			VARCHAR(64),
  CODINGSCHEMEDESIGNATOR	VARCHAR(64),
  CODINGSCHEMEVERSION		VARCHAR(64),
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,    
  PAIS_UID			VARCHAR(64)   NOT NULL
);   
 


CREATE TABLE PAIS.PATIENT(
  PATIENT_ID 			DECIMAL(30,0) NOT NULL,
  PATIENTID 			VARCHAR(64),  
  SEX				VARCHAR(64),  
  BIRTHDATE			VARCHAR(64),  
  ETHNICGROUP			VARCHAR(64),
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,  
  PAIS_UID			VARCHAR(64)   NOT NULL     
);


-- Removed: CALCULATION_FLAT
-- Added:
 CREATE TABLE PAIS.CALCULATION_DICTIONARY(
  DICTIONARY_ID			DECIMAL(30,0) NOT NULL, 
  METHODNAME			VARCHAR(64),
  CALCULATION_NAME		VARCHAR(64),  
  CODEVALUE			VARCHAR(64),  
  CODEMEANING			VARCHAR(64),
  CODINGSCHEMEDESIGNATOR	VARCHAR(64),
  CODINGSCHEMEVERSION		VARCHAR(64),
  DESCRIPTION			VARCHAR(512),
  DATATYPE			VARCHAR(64),
  UNITOFMEASURE			VARCHAR(64)
);

-- Added:
 CREATE TABLE PAIS.OBSERVATION_DICTIONARY(
  DICTIONARY_ID			DECIMAL(30,0) NOT NULL, 
  METHODNAME			VARCHAR(64),
  OBSERVATION_NAME		VARCHAR(64),  
  CODEVALUE			VARCHAR(64),  
  CODEMEANING			VARCHAR(64),
  CODINGSCHEMEDESIGNATOR	VARCHAR(64),
  CODINGSCHEMEVERSION		VARCHAR(64),
  DESCRIPTION			VARCHAR(512),
  DATATYPE			VARCHAR(64),
  UNITOFMEASURE			VARCHAR(64)
);


  
   CREATE TABLE PAIS.OBSERVATION_QUANTIFICATION_ORDINAL(
    OBSERVATION_ID 		DECIMAL(30,0) NOT NULL,
    OBSERVATION_NAME		VARCHAR(64),
    ANNOTATORCONFIDENCE		DOUBLE,
    
    QUANTIFICATION_ID		DECIMAL(30,0) NOT NULL,
    QUANTIFICATION_NAME		VARCHAR(64),
    QUANTIFICATION_VALUE	DOUBLE,
    QUANTIFICATION_DATATYPE	VARCHAR(64),
    PROVENANCE_ID		DECIMAL(30,0),
    MARKUP_ID			DECIMAL(30,0),

    ANNOTATION_ID		DECIMAL(30,0) NOT NULL,   
    TILENAME			VARCHAR(64) NOT NULL,    
    PAIS_UID			VARCHAR(64)   NOT NULL,    
    OBSERVATION_DICTIONARY_ID   DECIMAL(30,0)
 ) 
COMPRESS YES
IN SPATIALTBS32K;


   CREATE TABLE PAIS.OBSERVATION_QUANTIFICATION_NOMINAL(
    OBSERVATION_ID 		DECIMAL(30,0) NOT NULL,
    OBSERVATION_NAME		VARCHAR(64),
    ANNOTATORCONFIDENCE		DOUBLE,
    
    QUANTIFICATION_ID		DECIMAL(30,0) NOT NULL,
    QUANTIFICATION_NAME		VARCHAR(64),
    QUANTIFICATION_VALUE	VARCHAR(64),
    PROVENANCE_ID		DECIMAL(30,0),
    MARKUP_ID			DECIMAL(30,0),

    ANNOTATION_ID		DECIMAL(30,0) NOT NULL,   
    TILENAME			VARCHAR(64) NOT NULL,    
    PAIS_UID			VARCHAR(64)   NOT NULL,    
    OBSERVATION_DICTIONARY_ID   DECIMAL(30,0)
 ) 
COMPRESS YES
IN SPATIALTBS32K;
 
 
CREATE TABLE PAIS.ANNOTATION_MARKUP(
    ANNOTATION_ID		DECIMAL(30,0) NOT NULL,  
    MARKUP_ID			DECIMAL(30,0) NOT NULL,
    PAIS_UID			VARCHAR(64)   NOT NULL
 ) IN SPATIALTBS32K;


  


CREATE TABLE PAIS.PROVENANCE(
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL,    
  SCOPE				VARCHAR(64),    
  PAIS_UID 			VARCHAR(64) NOT NULL   
);


CREATE TABLE PAIS.ALGORITHM(
  ALGORITHM_ID			DECIMAL(30,0) NOT NULL,    
  NAME				VARCHAR(64),
  VERSION			VARCHAR(64),
  URI				VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL,  
  PAIS_UID 			VARCHAR(64)   NOT NULL 
);  

CREATE TABLE PAIS.PARAMETER(
  PARAMETER_ID			DECIMAL(30,0) NOT NULL,    
  NAME				VARCHAR(64),
  VALUE				VARCHAR(64),
  DATATYPE			VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL,    
  ALGORITHM_ID			DECIMAL(30,0) NOT NULL, 
  PAIS_UID 			VARCHAR(64)   NOT NULL   
);  
  

CREATE TABLE PAIS.INPUTFILEREFERENCE(
  INPUTFILEREFERENCE_ID 	DECIMAL(30,0) NOT NULL,    
  FILEREFERENCE			VARCHAR(64),
  URI				VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL, 
  ALGORITHM_ID			DECIMAL(30,0) NOT NULL,      
  PAIS_UID 			VARCHAR(64)   NOT NULL    
);


 CREATE TABLE PAIS.CALCULATION_FLAT(
  ANNOTATION_ID			DECIMAL(30,0) NOT NULL,  
  ANNOTATION_NAME		VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0),
  MARKUP_ID			DECIMAL(30,0) NOT NULL, 
  TILENAME			VARCHAR(64)   NOT NULL,
  PAIS_UID			VARCHAR(64)   NOT NULL,  
  CALCULATION_DICTIONARY_ID	DECIMAL(30,0)--FEATUREREPLACEMENT 
 ) 
COMPRESS YES
IN SPATIALTBS32K
;

CREATE TABLE PAIS.TEMPLATE(
   TEMPLATENAME    VARCHAR(100) NOT NULL UNIQUE,
   DESCRIPTION VARCHAR(1000),
   LASTSELECTTIME TIMESTAMP
);
CREATE TABLE PAIS.FEATURES(
FEATURENAME VARCHAR(100) NOT NULL UNIQUE,
DESCRIPTION VARCHAR(1000),
TYPE VARCHAR(30) NOT NULL
);

CREATE TABLE PAIS.TEMPLATEFEATURESRL(
FEATURENAME VARCHAR(100) NOT NULL,
TEMPLATENAME VARCHAR(100) NOT NULL
);

CREATE TABLE PAIS.DLMSTATUS(
   WORKSTATUS INTEGER,
   LASTHEARTBEAT TIMESTAMP
);


--NEWDROPTABLE

--NEWMARKUPTABLE

--INSERTTEMPLATESQL

--INSERTFEATURESQL

--INSERTTFRL